### ISSUE TITLE
`max_memory` ignored when loading BLOOM with `from_pretrained`

### ISSUE THREAD

**Issue by tannonk** [huggingface/accelerate#1103]
### System Info

```Shell
- `Accelerate` version: 0.16.0
- Platform: Linux-5.15.0-33-generic-x86_64-with-glibc2.31
- Python version: 3.9.16
- Numpy version: 1.24.2
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- `Accelerate` default config:
        Not found

- transformers: 4.27.0.dev0
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

**Issue:** 

Loading BLOOM (176B) for inference on 4x80GB A100 GPUs and 400GB+ CPU RAM fails with CUDA OOM.

```
model = AutoModelForCausalLM.from_pretrained(
    "bigscience/bloom" 
    device_map="auto", 
    load_in_8bit=True, 
    torch_dtype=torch.float16, 
    max_memory={0: '31GB', 1: '63GB', 2: '63GB', 3: '63GB', 'cpu': '400GB'},
    offload_state_dict=True,
    offload_folder="/scratch/offload"
    )
```
**Error description:**

During loading of the checkpoint shards, CUDA OOM error is raised:
```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 784.00 MiB (GPU 0; 79.17 GiB total capacity; 77.93 GiB already allocated; 317.81 MiB free; 77.93 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

Monitoring `nvidia-smi` shows that the GPU memory exceeds that specified with `max_memory`, but it's not clear to me why this argument is being ignored.

After reading through the docs and related issues (huggingface/accelerate#483, huggingface/accelerate#864), I can't yet see where the problem is. 4*80GB GPUs should more than enough to load the model in 8bit-int (~157GB), right?

**Things I've tried:**

- Setting environment variable `max_split_size_mb` as suggested by the error message.
- Specifying `device_map="balanced_low_0"` in `from_pretrained()`
- Specifying `offload_state_dict=False` in `from_pretrained()`
- Specifying `load_in_8bit=False` in `from_pretrained()` (manages to load the checkpoint shards but fails on the forward pass)

### Expected behavior

8bit inference with BLOOM on 4*80GB A100 GPUs with 400GB+ CPU RAM.

---

Any clarification on the correct use of `max_memory` and loading BLOOM in `8bit-int` would be greatly appreciated!

**Comment by tannonk** [comment]
Actually, scratch that! I found a bug by stepping through the code with PDB :grimacing:

My `max_memory` dict was actually being passed as a `None` object, and the argument was thus not even being set... *facepalm* 

As you were. Carry on the good work. :dizzy:
