### ISSUE TITLE
"accelerate test" hangs after initialization and then timeouts

### ISSUE THREAD

**Issue by luk-s** [huggingface/accelerate#1209]
#### GPU specification 
```Shell
- Cluster with 6 NVIDIA RTX A6000 GPUs
```
#### accelerate env output
```Shell
- `Accelerate` version: 0.17.1
- Platform: Linux-5.4.0-139-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- Numpy version: 1.24.2
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- `Accelerate` default config:
	- compute_environment: LOCAL_MACHINE
	- distributed_type: MULTI_GPU
	- mixed_precision: no
	- use_cpu: False
	- num_processes: 4
	- machine_rank: 0
	- num_machines: 1
	- gpu_ids: 4,5,6,7
	- rdzv_backend: static
	- same_network: True
	- main_training_function: main
	- deepspeed_config: {}
	- fsdp_config: {}
	- megatron_lm_config: {}
	- downcast_bf16: no
	- tpu_use_cluster: False
	- tpu_use_sudo: False
	- tpu_env: []
	- dynamo_config: {}
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

(I hope I provide enough debug information. If you need anything else, just let me know!)

#### Maybe relevant environment variables:
`CUDA_VISIBLE_DEVICES=4,5,6,7`
`NCCL_DEBUG=INFO`

#### Command:
 `accelerate test` using the default configuration posted above 

#### Result:
Test script successfully manages to initialize the workers (all log lines until the 4 "...Init COMPLETE" lines) and then does nothing for about 30minutes before finally being killed by a Watchdog thread. My 4 GPUs are 100% utilized during this time.

#### Debug output:
```
Running:  accelerate-launch /local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/test_utils/scripts/test_script.py
stderr: The following values were not passed to `accelerate launch` and had defaults used instead:
stderr: 	`--dynamo_backend` was set to a value of `'no'`
stderr: To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
stdout: Distributed environment: MULTI_GPU  Backend: nccl
stdout: Num processes: 4
stdout: Process index: 1
stdout: Local process index: 1
stdout: Device: cuda:1
stdout: 
stdout: Mixed precision type: no
stdout: 
stdout: Distributed environment: MULTI_GPU  Backend: nccl
stdout: Num processes: 4
stdout: Process index: 3
stdout: Local process index: 3
stdout: Device: cuda:3
stdout: 
stdout: Mixed precision type: no
stdout: 
stdout: **Initialization**
stdout: Testing, testing. 1, 2, 3.
stdout: Distributed environment: MULTI_GPU  Backend: nccl
stdout: Num processes: 4
stdout: Process index: 0
stdout: Local process index: 0
stdout: Device: cuda:0
stdout: 
stdout: Mixed precision type: no
stdout: 
stdout: 
stdout: **Test process execution**
stdout: Distributed environment: MULTI_GPU  Backend: nccl
stdout: Num processes: 4
stdout: Process index: 2
stdout: Local process index: 2
stdout: Device: cuda:2
stdout: 
stdout: Mixed precision type: no
stdout: 
stdout: server_anonymized:4033008:4033008 [0] NCCL INFO Bootstrap : Using enp226s0f0:129.132.107.104<0>
stdout: server_anonymized:4033008:4033008 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
stdout: server_anonymized:4033008:4033008 [0] NCCL INFO cudaDriverVersion 11070
stdout: NCCL version 2.14.3+cuda11.7
stdout: server_anonymized:4033011:4033011 [3] NCCL INFO cudaDriverVersion 11070
stdout: server_anonymized:4033010:4033010 [2] NCCL INFO cudaDriverVersion 11070
stdout: server_anonymized:4033009:4033009 [1] NCCL INFO cudaDriverVersion 11070
stdout: server_anonymized:4033011:4033011 [3] NCCL INFO Bootstrap : Using enp226s0f0:129.132.107.104<0>
stdout: server_anonymized:4033011:4033011 [3] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Failed to open libibverbs.so[.1]
stdout: server_anonymized:4033011:4033042 [3] NCCL INFO Failed to open libibverbs.so[.1]
stdout: server_anonymized:4033010:4033010 [2] NCCL INFO Bootstrap : Using enp226s0f0:129.132.107.104<0>
stdout: server_anonymized:4033010:4033010 [2] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO NET/Socket : Using [0]enp226s0f0:129.132.107.104<0>
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Using network Socket
stdout: server_anonymized:4033009:4033009 [1] NCCL INFO Bootstrap : Using enp226s0f0:129.132.107.104<0>
stdout: server_anonymized:4033009:4033009 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
stdout: server_anonymized:4033011:4033042 [3] NCCL INFO NET/Socket : Using [0]enp226s0f0:129.132.107.104<0>
stdout: server_anonymized:4033011:4033042 [3] NCCL INFO Using network Socket
stdout: server_anonymized:4033010:4033043 [2] NCCL INFO Failed to open libibverbs.so[.1]
stdout: server_anonymized:4033010:4033043 [2] NCCL INFO NET/Socket : Using [0]enp226s0f0:129.132.107.104<0>
stdout: server_anonymized:4033010:4033043 [2] NCCL INFO Using network Socket
stdout: server_anonymized:4033009:4033044 [1] NCCL INFO Failed to open libibverbs.so[.1]
stdout: server_anonymized:4033009:4033044 [1] NCCL INFO NET/Socket : Using [0]enp226s0f0:129.132.107.104<0>
stdout: server_anonymized:4033009:4033044 [1] NCCL INFO Using network Socket
stdout: server_anonymized:4033009:4033044 [1] NCCL INFO Setting affinity for GPU 5 to ffff,00000000,00000000,00000000,0000ffff,00000000,00000000,00000000
stdout: server_anonymized:4033011:4033042 [3] NCCL INFO Setting affinity for GPU 7 to ffff,00000000,00000000,00000000,0000ffff,00000000,00000000
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Setting affinity for GPU 4 to ffff0000,00000000,00000000,00000000,ffff0000,00000000,00000000,00000000
stdout: server_anonymized:4033010:4033043 [2] NCCL INFO Setting affinity for GPU 6 to ffff0000,00000000,00000000,00000000,ffff0000,00000000,00000000
stdout: server_anonymized:4033011:4033042 [3] NCCL INFO Trees [0] -1/-1/-1->3->2 [1] 2/-1/-1->3->0 [2] 0/-1/-1->3->2 [3] 2/-1/-1->3->-1 [4] -1/-1/-1->3->2 [5] 2/-1/-1->3->0 [6] 0/-1/-1->3->2 [7] 2/-1/-1->3->-1
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Channel 00/08 :    0   1   2   3
stdout: server_anonymized:4033010:4033043 [2] NCCL INFO Trees [0] 3/-1/-1->2->1 [1] -1/-1/-1->2->3 [2] 3/-1/-1->2->-1 [3] 1/-1/-1->2->3 [4] 3/-1/-1->2->1 [5] -1/-1/-1->2->3 [6] 3/-1/-1->2->-1 [7] 1/-1/-1->2->3
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Channel 01/08 :    0   1   2   3
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Channel 02/08 :    0   3   2   1
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Channel 03/08 :    0   3   2   1
stdout: server_anonymized:4033009:4033044 [1] NCCL INFO Trees [0] 2/-1/-1->1->0 [1] 0/-1/-1->1->-1 [2] -1/-1/-1->1->0 [3] 0/-1/-1->1->2 [4] 2/-1/-1->1->0 [5] 0/-1/-1->1->-1 [6] -1/-1/-1->1->0 [7] 0/-1/-1->1->2
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Channel 04/08 :    0   1   2   3
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Channel 05/08 :    0   1   2   3
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Channel 06/08 :    0   3   2   1
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Channel 07/08 :    0   3   2   1
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 3/-1/-1->0->1 [2] 1/-1/-1->0->3 [3] -1/-1/-1->0->1 [4] 1/-1/-1->0->-1 [5] 3/-1/-1->0->1 [6] 1/-1/-1->0->3 [7] -1/-1/-1->0->1
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Channel 00/0 : 0[81000] -> 1[a1000] via P2P/IPC
stdout: server_anonymized:4033010:4033043 [2] NCCL INFO Channel 00/0 : 2[c1000] -> 3[e1000] via P2P/IPC
stdout: server_anonymized:4033011:4033042 [3] NCCL INFO Channel 00/0 : 3[e1000] -> 0[81000] via P2P/IPC
stdout: server_anonymized:4033009:4033044 [1] NCCL INFO Channel 00/0 : 1[a1000] -> 2[c1000] via P2P/IPC
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Channel 01/0 : 0[81000] -> 1[a1000] via P2P/IPC
stdout: server_anonymized:4033010:4033043 [2] NCCL INFO Channel 01/0 : 2[c1000] -> 3[e1000] via P2P/IPC
stdout: server_anonymized:4033011:4033042 [3] NCCL INFO Channel 01/0 : 3[e1000] -> 0[81000] via P2P/IPC
stdout: server_anonymized:4033009:4033044 [1] NCCL INFO Channel 01/0 : 1[a1000] -> 2[c1000] via P2P/IPC
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Channel 04/0 : 0[81000] -> 1[a1000] via P2P/IPC
stdout: server_anonymized:4033010:4033043 [2] NCCL INFO Channel 04/0 : 2[c1000] -> 3[e1000] via P2P/IPC
stdout: server_anonymized:4033011:4033042 [3] NCCL INFO Channel 04/0 : 3[e1000] -> 0[81000] via P2P/IPC
stdout: server_anonymized:4033009:4033044 [1] NCCL INFO Channel 04/0 : 1[a1000] -> 2[c1000] via P2P/IPC
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Channel 05/0 : 0[81000] -> 1[a1000] via P2P/IPC
stdout: server_anonymized:4033010:4033043 [2] NCCL INFO Channel 05/0 : 2[c1000] -> 3[e1000] via P2P/IPC
stdout: server_anonymized:4033011:4033042 [3] NCCL INFO Channel 05/0 : 3[e1000] -> 0[81000] via P2P/IPC
stdout: server_anonymized:4033009:4033044 [1] NCCL INFO Channel 05/0 : 1[a1000] -> 2[c1000] via P2P/IPC
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Channel 02/0 : 0[81000] -> 3[e1000] via P2P/IPC
stdout: server_anonymized:4033010:4033043 [2] NCCL INFO Channel 02/0 : 2[c1000] -> 1[a1000] via P2P/IPC
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Channel 03/0 : 0[81000] -> 3[e1000] via P2P/IPC
stdout: server_anonymized:4033011:4033042 [3] NCCL INFO Channel 02/0 : 3[e1000] -> 2[c1000] via P2P/IPC
stdout: server_anonymized:4033010:4033043 [2] NCCL INFO Channel 03/0 : 2[c1000] -> 1[a1000] via P2P/IPC
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Channel 06/0 : 0[81000] -> 3[e1000] via P2P/IPC
stdout: server_anonymized:4033011:4033042 [3] NCCL INFO Channel 03/0 : 3[e1000] -> 2[c1000] via P2P/IPC
stdout: server_anonymized:4033010:4033043 [2] NCCL INFO Channel 06/0 : 2[c1000] -> 1[a1000] via P2P/IPC
stdout: server_anonymized:4033009:4033044 [1] NCCL INFO Channel 02/0 : 1[a1000] -> 0[81000] via P2P/IPC
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Channel 07/0 : 0[81000] -> 3[e1000] via P2P/IPC
stdout: server_anonymized:4033011:4033042 [3] NCCL INFO Channel 06/0 : 3[e1000] -> 2[c1000] via P2P/IPC
stdout: server_anonymized:4033010:4033043 [2] NCCL INFO Channel 07/0 : 2[c1000] -> 1[a1000] via P2P/IPC
stdout: server_anonymized:4033009:4033044 [1] NCCL INFO Channel 03/0 : 1[a1000] -> 0[81000] via P2P/IPC
stdout: server_anonymized:4033011:4033042 [3] NCCL INFO Channel 07/0 : 3[e1000] -> 2[c1000] via P2P/IPC
stdout: server_anonymized:4033009:4033044 [1] NCCL INFO Channel 06/0 : 1[a1000] -> 0[81000] via P2P/IPC
stdout: server_anonymized:4033009:4033044 [1] NCCL INFO Channel 07/0 : 1[a1000] -> 0[81000] via P2P/IPC
stdout: server_anonymized:4033011:4033042 [3] NCCL INFO Connected all rings
stdout: server_anonymized:4033010:4033043 [2] NCCL INFO Connected all rings
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Connected all rings
stdout: server_anonymized:4033009:4033044 [1] NCCL INFO Connected all rings
stdout: server_anonymized:4033010:4033043 [2] NCCL INFO Channel 02/0 : 2[c1000] -> 3[e1000] via P2P/IPC
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Channel 02/0 : 0[81000] -> 1[a1000] via P2P/IPC
stdout: server_anonymized:4033011:4033042 [3] NCCL INFO Channel 02/0 : 3[e1000] -> 0[81000] via P2P/IPC
stdout: server_anonymized:4033010:4033043 [2] NCCL INFO Channel 03/0 : 2[c1000] -> 3[e1000] via P2P/IPC
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Channel 03/0 : 0[81000] -> 1[a1000] via P2P/IPC
stdout: server_anonymized:4033010:4033043 [2] NCCL INFO Channel 06/0 : 2[c1000] -> 3[e1000] via P2P/IPC
stdout: server_anonymized:4033011:4033042 [3] NCCL INFO Channel 06/0 : 3[e1000] -> 0[81000] via P2P/IPC
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Channel 06/0 : 0[81000] -> 1[a1000] via P2P/IPC
stdout: server_anonymized:4033009:4033044 [1] NCCL INFO Channel 03/0 : 1[a1000] -> 2[c1000] via P2P/IPC
stdout: server_anonymized:4033010:4033043 [2] NCCL INFO Channel 07/0 : 2[c1000] -> 3[e1000] via P2P/IPC
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Channel 07/0 : 0[81000] -> 1[a1000] via P2P/IPC
stdout: server_anonymized:4033009:4033044 [1] NCCL INFO Channel 07/0 : 1[a1000] -> 2[c1000] via P2P/IPC
stdout: server_anonymized:4033011:4033042 [3] NCCL INFO Channel 00/0 : 3[e1000] -> 2[c1000] via P2P/IPC
stdout: server_anonymized:4033009:4033044 [1] NCCL INFO Channel 00/0 : 1[a1000] -> 0[81000] via P2P/IPC
stdout: server_anonymized:4033011:4033042 [3] NCCL INFO Channel 01/0 : 3[e1000] -> 2[c1000] via P2P/IPC
stdout: server_anonymized:4033009:4033044 [1] NCCL INFO Channel 01/0 : 1[a1000] -> 0[81000] via P2P/IPC
stdout: server_anonymized:4033011:4033042 [3] NCCL INFO Channel 04/0 : 3[e1000] -> 2[c1000] via P2P/IPC
stdout: server_anonymized:4033009:4033044 [1] NCCL INFO Channel 04/0 : 1[a1000] -> 0[81000] via P2P/IPC
stdout: server_anonymized:4033010:4033043 [2] NCCL INFO Channel 00/0 : 2[c1000] -> 1[a1000] via P2P/IPC
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Channel 01/0 : 0[81000] -> 3[e1000] via P2P/IPC
stdout: server_anonymized:4033011:4033042 [3] NCCL INFO Channel 05/0 : 3[e1000] -> 2[c1000] via P2P/IPC
stdout: server_anonymized:4033009:4033044 [1] NCCL INFO Channel 05/0 : 1[a1000] -> 0[81000] via P2P/IPC
stdout: server_anonymized:4033010:4033043 [2] NCCL INFO Channel 04/0 : 2[c1000] -> 1[a1000] via P2P/IPC
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Channel 05/0 : 0[81000] -> 3[e1000] via P2P/IPC
stdout: server_anonymized:4033009:4033044 [1] NCCL INFO Connected all trees
stdout: server_anonymized:4033009:4033044 [1] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
stdout: server_anonymized:4033009:4033044 [1] NCCL INFO 8 coll channels, 8 p2p channels, 2 p2p channels per peer
stdout: server_anonymized:4033010:4033043 [2] NCCL INFO Connected all trees
stdout: server_anonymized:4033010:4033043 [2] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
stdout: server_anonymized:4033010:4033043 [2] NCCL INFO 8 coll channels, 8 p2p channels, 2 p2p channels per peer
stdout: server_anonymized:4033011:4033042 [3] NCCL INFO Connected all trees
stdout: server_anonymized:4033011:4033042 [3] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
stdout: server_anonymized:4033011:4033042 [3] NCCL INFO 8 coll channels, 8 p2p channels, 2 p2p channels per peer
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO Connected all trees
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO 8 coll channels, 8 p2p channels, 2 p2p channels per peer
stdout: server_anonymized:4033008:4033041 [0] NCCL INFO comm 0x427f3950 rank 0 nranks 4 cudaDev 0 busId 81000 - Init COMPLETE
stdout: server_anonymized:4033009:4033044 [1] NCCL INFO comm 0x41fb3a30 rank 1 nranks 4 cudaDev 1 busId a1000 - Init COMPLETE
stdout: server_anonymized:4033010:4033043 [2] NCCL INFO comm 0x42979100 rank 2 nranks 4 cudaDev 2 busId c1000 - Init COMPLETE
stdout: server_anonymized:4033011:4033042 [3] NCCL INFO comm 0x42804810 rank 3 nranks 4 cudaDev 3 busId e1000 - Init COMPLETE
stderr: [E ProcessGroupNCCL.cpp:821] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1808127 milliseconds before timing out.
stdout: server_anonymized:4033010:4033048 [2] NCCL INFO [Service thread] Connection closed by localRank 2
stdout: server_anonymized:4033010:4033021 [0] NCCL INFO comm 0x42979100 rank 2 nranks 4 cudaDev 2 busId c1000 - Abort COMPLETE
stderr: [E ProcessGroupNCCL.cpp:821] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1808212 milliseconds before timing out.
stderr: Traceback (most recent call last):
stderr:   File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/test_utils/scripts/test_script.py", line 407, in <module>
stderr:     main()
stderr:   File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/test_utils/scripts/test_script.py", line 384, in main
stderr:     rng_sync_check()
stderr:   File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/test_utils/scripts/test_script.py", line 112, in rng_sync_check
stderr:     synchronize_rng_states(["torch"])
stderr:   File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/utils/random.py", line 89, in synchronize_rng_states
stderr:     synchronize_rng_state(RNGType(rng_type), generator=generator)
stderr:   File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/utils/random.py", line 71, in synchronize_rng_state
stderr:     torch.distributed.broadcast(rng_state, 0)
stderr:   File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1400, in broadcast
stderr:     [E ProcessGroupNCCL.cpp:821] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1808213 milliseconds before timing out.
stderr: work = default_pg.broadcast([tensor], opts)
stderr: RuntimeError: NCCL communicator was aborted on rank 2.  Original reason for failure was: [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1808127 milliseconds before timing out.
stderr: [E ProcessGroupNCCL.cpp:821] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1808221 milliseconds before timing out.
stderr: [E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
stderr: [E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
stderr: terminate called after throwing an instance of 'std::runtime_error'
stderr:   what():  [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1808127 milliseconds before timing out.
stdout: server_anonymized:4033009:4033045 [1] NCCL INFO [Service thread] Connection closed by localRank 1
stdout: server_anonymized:4033009:4033030 [0] NCCL INFO comm 0x41fb3a30 rank 1 nranks 4 cudaDev 1 busId a1000 - Abort COMPLETE
stderr: Traceback (most recent call last):
stderr:   File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/test_utils/scripts/test_script.py", line 407, in <module>
stdout: server_anonymized:4033011:4033046 [3] NCCL INFO [Service thread] Connection closed by localRank 3
stderr:     main()
stderr:   File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/test_utils/scripts/test_script.py", line 384, in main
stderr:     rng_sync_check()
stderr:   File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/test_utils/scripts/test_script.py", line 112, in rng_sync_check
stderr:     synchronize_rng_states(["torch"])
stderr:   File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/utils/random.py", line 89, in synchronize_rng_states
stderr:     synchronize_rng_state(RNGType(rng_type), generator=generator)
stderr:   File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/utils/random.py", line 71, in synchronize_rng_state
stderr:     torch.distributed.broadcast(rng_state, 0)
stderr:   File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1400, in broadcast
stderr:     work = default_pg.broadcast([tensor], opts)
stderr: RuntimeError: NCCL communicator was aborted on rank 1.  Original reason for failure was: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1808221 milliseconds before timing out.
stderr: Traceback (most recent call last):
stderr:   File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/test_utils/scripts/test_script.py", line 407, in <module>
stderr:     main()
stderr:   File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/test_utils/scripts/test_script.py", line 384, in main
stderr:     rng_sync_check()
stderr:   File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/test_utils/scripts/test_script.py", line 112, in rng_sync_check
stderr:     synchronize_rng_states(["torch"])
stderr:   File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/utils/random.py", line 89, in synchronize_rng_states
stderr:     synchronize_rng_state(RNGType(rng_type), generator=generator)
stderr:   File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/utils/random.py", line 78, in synchronize_rng_state
stderr:     torch.set_rng_state(rng_state)
stderr:   File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/torch/random.py", line 18, in set_rng_state
stderr:     default_generator.set_state(new_state)
stderr: RuntimeError: Invalid mt19937 state
stderr: [E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
stderr: [E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
stderr: terminate called after throwing an instance of 'std::runtime_error'
stderr:   what():  [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1808221 milliseconds before timing out.
stdout: server_anonymized:4033011:4033026 [0] NCCL INFO comm 0x42804810 rank 3 nranks 4 cudaDev 3 busId e1000 - Abort COMPLETE
stderr: [E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
stderr: [E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
stderr: terminate called after throwing an instance of 'std::runtime_error'
stderr:   what():  [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1808213 milliseconds before timing out.
stdout: server_anonymized:4033008:4033047 [0] NCCL INFO [Service thread] Connection closed by localRank 0
stdout: 
stdout: **Test random number generator synchronization**
stdout: server_anonymized:4033008:4033028 [0] NCCL INFO comm 0x427f3950 rank 0 nranks 4 cudaDev 0 busId 81000 - Abort COMPLETE
stderr: [E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
stderr: [E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
stderr: terminate called after throwing an instance of 'std::runtime_error'
stderr:   what():  [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1808212 milliseconds before timing out.
stderr: ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 4033008) of binary: /local/home/path_anonymized/legal/.venv/bin/python3
stderr: Traceback (most recent call last):
stderr:   File "/local/home/path_anonymized/legal/.venv/bin/accelerate-launch", line 8, in <module>
stderr:     sys.exit(main())
stderr:   File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/commands/launch.py", line 921, in main
stderr:     launch_command(args)
stderr:   File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/commands/launch.py", line 906, in launch_command
stderr:     multi_gpu_launcher(args)
stderr:   File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/commands/launch.py", line 599, in multi_gpu_launcher
stderr:     distrib_run.run(args)
stderr:   File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
stderr:     elastic_launch(
stderr:   File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
stderr:     return launch_agent(self._config, self._entrypoint, list(args))
stderr:   File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
stderr:     raise ChildFailedError(
stderr: torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
stderr: ============================================================
stderr: /local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/test_utils/scripts/test_script.py FAILED
stderr: ------------------------------------------------------------
stderr: Failures:
stderr: [1]:
stderr:   time      : 2023-03-18_11:41:57
stderr:   host      : server_anonymized.country_code_anonymized
stderr:   rank      : 1 (local_rank: 1)
stderr:   exitcode  : -6 (pid: 4033009)
stderr:   error_file: <N/A>
stderr:   traceback : Signal 6 (SIGABRT) received by PID 4033009
stderr: [2]:
stderr:   time      : 2023-03-18_11:41:57
stderr:   host      : server_anonymized.country_code_anonymized
stderr:   rank      : 2 (local_rank: 2)
stderr:   exitcode  : -6 (pid: 4033010)
stderr:   error_file: <N/A>
stderr:   traceback : Signal 6 (SIGABRT) received by PID 4033010
stderr: [3]:
stderr:   time      : 2023-03-18_11:41:57
stderr:   host      : server_anonymized.country_code_anonymized
stderr:   rank      : 3 (local_rank: 3)
stderr:   exitcode  : -6 (pid: 4033011)
stderr:   error_file: <N/A>
stderr:   traceback : Signal 6 (SIGABRT) received by PID 4033011
stderr: ------------------------------------------------------------
stderr: Root Cause (first observed failure):
stderr: [0]:
stderr:   time      : 2023-03-18_11:41:57
stderr:   host      : server_anonymized.country_code_anonymized
stderr:   rank      : 0 (local_rank: 0)
stderr:   exitcode  : -6 (pid: 4033008)
stderr:   error_file: <N/A>
stderr:   traceback : Signal 6 (SIGABRT) received by PID 4033008
stderr: ============================================================
Traceback (most recent call last):
  File "/local/home/path_anonymized/legal/.venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/commands/test.py", line 54, in test_command
    result = execute_subprocess_async(cmd, env=os.environ.copy())
  File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/test_utils/testing.py", line 359, in execute_subprocess_async
    raise RuntimeError(
RuntimeError: 'accelerate-launch /local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/test_utils/scripts/test_script.py' failed with returncode 1

The combined stderr from workers follows:
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
[E ProcessGroupNCCL.cpp:821] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1808127 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:821] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1808212 milliseconds before timing out.
Traceback (most recent call last):
  File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/test_utils/scripts/test_script.py", line 407, in <module>
    main()
  File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/test_utils/scripts/test_script.py", line 384, in main
    rng_sync_check()
  File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/test_utils/scripts/test_script.py", line 112, in rng_sync_check
    synchronize_rng_states(["torch"])
  File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/utils/random.py", line 89, in synchronize_rng_states
    synchronize_rng_state(RNGType(rng_type), generator=generator)
  File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/utils/random.py", line 71, in synchronize_rng_state
    torch.distributed.broadcast(rng_state, 0)
  File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1400, in broadcast
    [E ProcessGroupNCCL.cpp:821] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1808213 milliseconds before timing out.
work = default_pg.broadcast([tensor], opts)
RuntimeError: NCCL communicator was aborted on rank 2.  Original reason for failure was: [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1808127 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:821] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1808221 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1808127 milliseconds before timing out.
Traceback (most recent call last):
  File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/test_utils/scripts/test_script.py", line 407, in <module>
    main()
  File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/test_utils/scripts/test_script.py", line 384, in main
    rng_sync_check()
  File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/test_utils/scripts/test_script.py", line 112, in rng_sync_check
    synchronize_rng_states(["torch"])
  File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/utils/random.py", line 89, in synchronize_rng_states
    synchronize_rng_state(RNGType(rng_type), generator=generator)
  File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/utils/random.py", line 71, in synchronize_rng_state
    torch.distributed.broadcast(rng_state, 0)
  File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1400, in broadcast
    work = default_pg.broadcast([tensor], opts)
RuntimeError: NCCL communicator was aborted on rank 1.  Original reason for failure was: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1808221 milliseconds before timing out.
Traceback (most recent call last):
  File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/test_utils/scripts/test_script.py", line 407, in <module>
    main()
  File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/test_utils/scripts/test_script.py", line 384, in main
    rng_sync_check()
  File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/test_utils/scripts/test_script.py", line 112, in rng_sync_check
    synchronize_rng_states(["torch"])
  File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/utils/random.py", line 89, in synchronize_rng_states
    synchronize_rng_state(RNGType(rng_type), generator=generator)
  File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/utils/random.py", line 78, in synchronize_rng_state
    torch.set_rng_state(rng_state)
  File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/torch/random.py", line 18, in set_rng_state
    default_generator.set_state(new_state)
RuntimeError: Invalid mt19937 state
[E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1808221 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1808213 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1808212 milliseconds before timing out.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 4033008) of binary: /local/home/path_anonymized/legal/.venv/bin/python3
Traceback (most recent call last):
  File "/local/home/path_anonymized/legal/.venv/bin/accelerate-launch", line 8, in <module>
    sys.exit(main())
  File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/commands/launch.py", line 921, in main
    launch_command(args)
  File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/commands/launch.py", line 906, in launch_command
    multi_gpu_launcher(args)
  File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/commands/launch.py", line 599, in multi_gpu_launcher
    distrib_run.run(args)
  File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/local/home/path_anonymized/legal/.venv/lib/python3.8/site-packages/accelerate/test_utils/scripts/test_script.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-03-18_11:41:57
  host      : server_anonymized.country_code_anonymized
  rank      : 1 (local_rank: 1)
  exitcode  : -6 (pid: 4033009)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 4033009
[2]:
  time      : 2023-03-18_11:41:57
  host      : server_anonymized.country_code_anonymized
  rank      : 2 (local_rank: 2)
  exitcode  : -6 (pid: 4033010)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 4033010
[3]:
  time      : 2023-03-18_11:41:57
  host      : server_anonymized.country_code_anonymized
  rank      : 3 (local_rank: 3)
  exitcode  : -6 (pid: 4033011)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 4033011
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-03-18_11:41:57
  host      : server_anonymized.country_code_anonymized
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 4033008)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 4033008
============================================================

```

#### Example GPU utilization output during waiting time (GPUs 4-7 are mine):

```
> nvidia-smi -l
+-----------------------------------------------------------------------------+
Sat Mar 18 11:14:09 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.86.01    Driver Version: 515.86.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A6000    On   | 00000000:01:00.0 Off |                  Off |
| 52%   71C    P2   158W / 300W |   6798MiB / 49140MiB |     32%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX A6000    On   | 00000000:23:00.0 Off |                  Off |
| 30%   37C    P8    27W / 300W |      3MiB / 49140MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA RTX A6000    On   | 00000000:41:00.0 Off |                  Off |
| 30%   37C    P8    21W / 300W |      3MiB / 49140MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA RTX A6000    On   | 00000000:61:00.0 Off |                  Off |
| 30%   36C    P8    21W / 300W |      3MiB / 49140MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  NVIDIA RTX A6000    On   | 00000000:81:00.0 Off |                  Off |
| 30%   49C    P2   101W / 300W |    968MiB / 49140MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  NVIDIA RTX A6000    On   | 00000000:A1:00.0 Off |                  Off |
| 30%   48C    P2    97W / 300W |    968MiB / 49140MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  NVIDIA RTX A6000    On   | 00000000:C1:00.0 Off |                  Off |
| 30%   48C    P2    98W / 300W |    968MiB / 49140MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  NVIDIA RTX A6000    On   | 00000000:E1:00.0 Off |                  Off |
| 30%   49C    P2   100W / 300W |    968MiB / 49140MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A   3225993      C   ...r/whisper/venv/bin/python     6795MiB |
|    4   N/A  N/A   4033008      C   ...s/legal/.venv/bin/python3      965MiB |
|    5   N/A  N/A   4033009      C   ...s/legal/.venv/bin/python3      965MiB |
|    6   N/A  N/A   4033010      C   ...s/legal/.venv/bin/python3      965MiB |
|    7   N/A  N/A   4033011      C   ...s/legal/.venv/bin/python3      965MiB |
+-----------------------------------------------------------------------------+
```

#### ifconfig output

```
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 10.233.0.1  netmask 255.255.255.0  broadcast 10.233.0.255
        ether 02:42:c1:1b:ec:7a  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp194s0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether d8:5e:d3:02:b6:4e  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp226s0f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 129.anonymized  netmask 255.255.255.240  broadcast 129.anonymized
        inet6 fe80::da5e:d3ff:fe84:7c86  prefixlen 64  scopeid 0x20<link>
        ether d8:5e:d3:84:7c:86  txqueuelen 1000  (Ethernet)
        RX packets 813935855  bytes 962127067473 (962.1 GB)
        RX errors 0  dropped 0  overruns 34579  frame 0
        TX packets 928554400  bytes 1291709690759 (1.2 TB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xa4420000-a443ffff  

enp226s0f1: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether d8:5e:d3:84:7c:87  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xa4400000-a441ffff  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 19176321  bytes 18116216570 (18.1 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 19176321  bytes 18116216570 (18.1 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

```

### Expected behavior

The test should run for a certain amount of time and then finish successfully.

Could it be that the test just didn't finish yet on my machine and some watchdog thread was a bit too eager and killed it prematurely after 30 minutes?

**Comment by luk-s** [comment]
Alright I was able to resolve the issue. Turns out that this had nothing to do with the accelerate library but appears to be an issue with the [IOMMU](https://en.wikipedia.org/wiki/Input%E2%80%93output_memory_management_unit) of my machine. There seem to be two main ways to resolve this issue:
 - Disable IOMMU via the following environment variable: `NCCL_P2P_DISABLE=1`   (That's the solution which worked for me. Taken from [this issue](https://github.com/pytorch/pytorch/issues/1637#issuecomment-730423426)
 - Disable IOMMU via grub (I didn't test that one but it seemed to have helped other people, see [this issue](https://github.com/pytorch/pytorch/issues/1637#issuecomment-338268158))
