### ISSUE TITLE
Multi-GPU setup overloads a single GPU instead of distributing the load

### ISSUE THREAD

**Issue by kirilllzaitsev** [huggingface/accelerate#1443]
Hi, I have a setup with 2 GPUs 12Gb each. Here is the config file I use:

```
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false 
```

With a single GPU (configured by CUDA_VISIBLE_DEVICES="0") the script runs without OOM. However, switching to the multi-GPU case, the same code and configs (e.g., batch size) result in the error:

```
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Fatal error condition occurred in /opt/vcpkg/buildtrees/aws-c-io/src/9e6648842a-364b708815.clean/source/event_loop.c:72: aws_thread_launch(&cleanup_thread, s_event_loop_destroy_async_thread_fn, el_group, &thread_options) == AWS_OP_SUCCESS
Exiting Application
################################################################################
Stack trace:
################################################################################
/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/site-packages/pyarrow/libarrow.so.900(+0x200af06) [0x7f5f84b8ff06]
/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/site-packages/pyarrow/libarrow.so.900(+0x20028e5) [0x7f5f84b878e5]
/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/site-packages/pyarrow/libarrow.so.900(+0x1f27e09) [0x7f5f84aace09]
/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/site-packages/pyarrow/libarrow.so.900(+0x200ba3d) [0x7f5f84b90a3d]
/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/site-packages/pyarrow/libarrow.so.900(+0x1f25948) [0x7f5f84aaa948]
/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/site-packages/pyarrow/libarrow.so.900(+0x200ba3d) [0x7f5f84b90a3d]
/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/site-packages/pyarrow/libarrow.so.900(+0x1ee0b46) [0x7f5f84a65b46]
/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/site-packages/pyarrow/libarrow.so.900(+0x194546a) [0x7f5f844ca46a]
/lib64/libc.so.6(+0x39ce9) [0x7f5ff7406ce9]
/lib64/libc.so.6(+0x39d37) [0x7f5ff7406d37]
/lib64/libc.so.6(__libc_start_main+0xfc) [0x7f5ff73ef55c]
/home/user/venvs/ssdc/bin/python() [0x4006fe]
Epoch 0:   0%|                                                                                                | 0/1000 [00:03<?, ?it/s]
Fatal error condition occurred in /opt/vcpkg/buildtrees/aws-c-io/src/9e6648842a-364b708815.clean/source/event_loop.c:72: aws_thread_launch(&cleanup_thread, s_event_loop_destroy_async_thread_fn, el_group, &thread_options) == AWS_OP_SUCCESS
Exiting Application
################################################################################
Stack trace:
################################################################################
/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/site-packages/pyarrow/libarrow.so.900(+0x200af06) [0x7fd5d272ef06]
/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/site-packages/pyarrow/libarrow.so.900(+0x20028e5) [0x7fd5d27268e5]
/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/site-packages/pyarrow/libarrow.so.900(+0x1f27e09) [0x7fd5d264be09]
/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/site-packages/pyarrow/libarrow.so.900(+0x200ba3d) [0x7fd5d272fa3d]
/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/site-packages/pyarrow/libarrow.so.900(+0x1f25948) [0x7fd5d2649948]
/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/site-packages/pyarrow/libarrow.so.900(+0x200ba3d) [0x7fd5d272fa3d]
/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/site-packages/pyarrow/libarrow.so.900(+0x1ee0b46) [0x7fd5d2604b46]
/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/site-packages/pyarrow/libarrow.so.900(+0x194546a) [0x7fd5d206946a]
/lib64/libc.so.6(+0x39ce9) [0x7fd644fa5ce9]
/lib64/libc.so.6(+0x39d37) [0x7fd644fa5d37]
/lib64/libc.so.6(__libc_start_main+0xfc) [0x7fd644f8e55c]
/home/user/venvs/ssdc/bin/python() [0x4006fe]
[12:11:44] ERROR    failed (exitcode: -6) local_rank: 0 (pid: 80069) of binary: 
/home/user/venvs/ssdc/bin/python                                                                   
[1]    65846 segmentation fault (core dumped)  accelerate launch  train.py 
```

Here is a log from nvidia-smi:

![image](https://github.com/huggingface/accelerate/assets/44346535/9605a444-a126-4529-8806-40a21a8d8e8c)

The load is unevenly distributed between GPUs, and at 12:11:29 the script fails with OOM.

Could you give some recipes for debugging where things might go wrong?

**Comment by exhyy** [comment]
Same issue. I tried to train a Control Net with 4 GPUs 12 GB each. OOM only occurs when resuming from a checkpoint with multi-GPU.

**Comment by sgugger** [comment]
It's hard to know without knowing the script you run, but it's very likely that you do not have enough RAM to load the model on the 2 processes: each process loads the model on the CPU then pass it on the GPU they have, so for a brief moment you need 2x the size of the model in CPU RAM.

**Comment by trieunus** [comment]
I have the same issue. I trained mT0-large with 4 * A100 GPU 80GB. After half an epoch, it throws OOM error saying that I need to allocate at least 90 GB for cuda:1, which seems to be something glaring.

**Comment by JunMa11** [comment]
@trieunus , the same issue here. have you solved it?

**Comment by exhyy** [comment]
@JunMa11 Yes, I have solved my problem by loading optimizer state to different GPUs in #1444

**Comment by JunMa11** [comment]
Hi @exhyy ,

Thanks for your reply very much.

I change the optimizer to 
`optimizer_state = torch.load(input_optimizer_file, map_location=map_location)` 
but still have the OOM issue. Would it be possible for you to take a look at my job file?

```bash
#!/bin/bash
#SBATCH --nodes=5
#SBATCH --ntasks=5
#SBATCH --cpus-per-task=24
#SBATCH --job-name=5nodes
#SBATCH --mem=200GB
#SBATCH --gres=gpu:4
#SBATCH --partition=a100
#SBATCH --output=logs/%x-%j.out
#SBATCH --error=logs/%x-%j.err
#SBATCH --time=10-00:00:00
#SBATCH --exclude=gpu182,gpu183,gpu184,gpu185,gpu186

set -x -e

# log the sbatch environment
echo "start time: $(date)"
echo "SLURM_JOBID="$SLURM_JOBID
echo "SLURM_JOB_NODELIST"=$SLURM_JOB_NODELIST
echo "SLURM_JOB_PARTITION"=$SLURM_JOB_PARTITION
echo "SLURM_NNODES"=$SLURM_NNODES
echo "SLURM_GPUS_ON_NODE"=$SLURM_GPUS_ON_NODE
echo "SLURM_SUBMIT_DIR"=$SLURM_SUBMIT_DIR

# Training setup
GPUS_PER_NODE=4
# so processes know who to talk to
MASTER_ADDR=$(scontrol show hostnames $SLURM_JOB_NODELIST | head -n 1)
MASTER_PORT=6000
NNODES=$SLURM_NNODES
NODE_RANK=$SLURM_PROCID 
WORLD_SIZE=$(($GPUS_PER_NODE*$NNODES))

export NCCL_IB_DISABLE=1

CMD=" \
    v2-1_mgpus_train_enc_dec.py \
    -task_name SAMViT-B-5nodes \
    -batch_size 8 \
    "

LAUNCHER="accelerate launch \
    --multi_gpu \
    --num_machines $NNODES \
    --num_processes $WORLD_SIZE \
    --main_process_ip "$MASTER_ADDR" \
    --main_process_port $MASTER_PORT \
    --num_processes $WORLD_SIZE \
    --machine_rank \$SLURM_PROCID \
    --role $SLURMD_NODENAME: \
    --rdzv_conf rdzv_backend=c10d \
    --max_restarts 3 \
    --tee 3 \
"


SRUN_ARGS=" \
    --wait=60 \
    --kill-on-bad-exit=1 \
    "

clear; srun $SRUN_ARGS --jobid $SLURM_JOB_ID bash -c "$LAUNCHER $CMD" 2>&1 | tee ./logs/%x-%j.txt

echo "END TIME: $(date)"

```

error log

```
[gpu187:2]:torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 176.00 MiB (GPU 2; 79.35 GiB total capacity; 40.99 GiB already allocated; 125.69 MiB free; 41.46 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 30352 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 30354 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 30361 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 30353 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 30357 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 30360 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 2 (pid: 30359) of binary: /h/junma/anaconda3/envs/medsam/bin/python
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 2 (pid: 30358) of binary: /h/junma/anaconda3/envs/medsam/bin/python

```

**Comment by exhyy** [comment]
@JunMa11 I’m sorry, I’m not an expert and I couldn’t find the problem with your script. @sgugger could you take a look here?
