### ISSUE TITLE
Falcon 40B inference

### ISSUE THREAD

**Issue by davidpodc** [huggingface/accelerate#1730]
### System Info

```Shell
- `Accelerate` version: 0.20.3
- Platform: Linux-5.4.0-153-generic-x86_64-with-glibc2.17
- Python version: 3.8.16
- Numpy version: 1.18.5
- PyTorch version (GPU?): 2.0.1+git8bfa463 (True)
- PyTorch XPU available: False
- System RAM: 251.75 GB
- GPU type: AMD Instinct MI210
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: no
        - use_cpu: False
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

```
from accelerate import init_empty_weights
from transformers import AutoConfig, AutoModelForCausalLM
from accelerate import load_checkpoint_and_dispatch
from transformers import AutoTokenizer
from accelerate import infer_auto_device_map
import pprint
import torch

checkpoint = "tiiuae/falcon-40b"
config = AutoConfig.from_pretrained(checkpoint, trust_remote_code=True)
dtype = torch.bfloat16

with init_empty_weights():
    model = AutoModelForCausalLM.from_config(config, trust_remote_code=True)
model.tie_weights()

device_map = infer_auto_device_map(model, max_memory={0: "63GiB", 1: "63GiB", "cpu": "250GiB"})
pprint.pprint(f'{device_map=}')

model = load_checkpoint_and_dispatch(
    model, checkpoint, device_map=device_map, dtype=dtype
)

tokenizer = AutoTokenizer.from_pretrained(checkpoint)
inputs = tokenizer("Hello, my name is", return_tensors="pt")
inputs = inputs.to(0)
output = model.generate(inputs["input_ids"])
res = tokenizer.decode(output[0].tolist())
print(f'{res=}')
```

Output:

```
root@mi210x2:/workspaces/tgi# python3 falcon.py
("device_map={'transformer.word_embeddings': 0, 'lm_head': 0, "
 "'transformer.h.0': 0, 'transformer.h.1': 0, 'transformer.h.2': 0, "
 "'transformer.h.3': 0, 'transformer.h.4': 0, 'transformer.h.5': 0, "
 "'transformer.h.6': 0, 'transformer.h.7': 0, 'transformer.h.8': 0, "
 "'transformer.h.9': 0, 'transformer.h.10': 0, 'transformer.h.11': 0, "
 "'transformer.h.12': 0, 'transformer.h.13': 0, 'transformer.h.14': 0, "
 "'transformer.h.15': 0, 'transformer.h.16': 0, 'transformer.h.17': 0, "
 "'transformer.h.18': 0, 'transformer.h.19': 0, 'transformer.h.20': 0, "
 "'transformer.h.21': 0, 'transformer.h.22': 0, 'transformer.h.23.ln_attn': 0, "
 "'transformer.h.23.ln_mlp': 0, 'transformer.h.23.self_attention': 0, "
 "'transformer.h.23.mlp.dense_h_to_4h': 0, 'transformer.h.23.mlp.act': 0, "
 "'transformer.h.23.mlp.dense_4h_to_h': 1, 'transformer.h.24': 1, "
 "'transformer.h.25': 1, 'transformer.h.26': 1, 'transformer.h.27': 1, "
 "'transformer.h.28': 1, 'transformer.h.29': 1, 'transformer.h.30': 1, "
 "'transformer.h.31': 1, 'transformer.h.32': 1, 'transformer.h.33': 1, "
 "'transformer.h.34': 1, 'transformer.h.35': 1, 'transformer.h.36': 1, "
 "'transformer.h.37': 1, 'transformer.h.38': 1, 'transformer.h.39': 1, "
 "'transformer.h.40': 1, 'transformer.h.41': 1, 'transformer.h.42': 1, "
 "'transformer.h.43': 1, 'transformer.h.44': 1, 'transformer.h.45': 1, "
 "'transformer.h.46': 1, 'transformer.h.47': 1, 'transformer.h.48.ln_attn': 1, "
 "'transformer.h.48.ln_mlp': 1, 'transformer.h.48.self_attention': 1, "
 "'transformer.h.49': 'cpu', 'transformer.h.50': 'cpu', 'transformer.h.51': "
 "'cpu', 'transformer.h.52': 'cpu', 'transformer.h.53': 'cpu', "
 "'transformer.h.54': 'cpu', 'transformer.h.55': 'cpu', 'transformer.h.56': "
 "'cpu', 'transformer.h.57': 'cpu', 'transformer.h.58': 'cpu', "
 "'transformer.h.59': 'cpu', 'transformer.ln_f': 'cpu', "
 "'transformer.h.48.mlp': 'cpu'}")
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:11 for open-end generation.
/opt/conda/envs/py_3.8/lib/python3.8/site-packages/transformers/generation/utils.py:1353: UserWarning: Using `max_length`'s default (20) to control the generation length. This behaviour is deprecated and will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
Traceback (most recent call last):
  File "falcon.py", line 29, in <module>
    output = model.generate(inputs["input_ids"])
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/transformers/generation/utils.py", line 1522, in generate
    return self.greedy_search(
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/transformers/generation/utils.py", line 2339, in greedy_search
    outputs = self(
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/falcon-40b/modelling_RW.py", line 759, in forward
    transformer_outputs = self.transformer(
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/falcon-40b/modelling_RW.py", line 654, in forward
    outputs = block(
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/falcon-40b/modelling_RW.py", line 414, in forward
    mlp_output + attention_output, residual, self.config.hidden_dropout, training=self.training
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!
```

### Expected behavior

Hello,

I'm experiencing a `RuntimeError` when trying to infer the Falcon 40B model across two AMD MI210 64GB GPUs. My initial approach was to use `device_map=auto` for automatic device placement, but that resulted in Out of Memory (OOM) errors.

To circumvent the OOM issue, I set the `max_memory` parameter for each GPU to 63GB. However, after making this adjustment, I ran into a new problem. Now, I get a `RuntimeError` that states tensors are located on different devices (`cuda:0` and `cuda:1`).

**Comment by sgugger** [comment]
You should use the integration into `Transformers` instead of computing the device map by hand (you can pass `device_map="auto"` and `max_memory` to the `from_pretrained` method).

Here your code is missing the `no_split_module_classes` argument that is automatically set by Transformers. It should contain the names of the blocks that should live on the same GPU exactly to avoid the error you are encountering :-) It seems to be `["DecoderLayer"]` reading the code of Falcon.

**Comment by davidpodc** [comment]
Yes, I was missing the `no_split_module_classes=['DecoderLayer']` in the `load_checkpoint_and_dispatch` function. It works now. Thank you!
