### ISSUE TITLE
One GPU is full that causes CUDA out of memory

### ISSUE THREAD

**Issue by ayaka14732** [huggingface/accelerate#200]
I am training on 1 machine with 4 GPUs.

```
Sun Nov 14 13:15:35 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.102.04   Driver Version: 450.102.04   CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:09.0 Off |                    0 |
| N/A   55C    P0   169W / 300W |   6740MiB / 32510MiB |     78%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:00:0A.0 Off |                    0 |
| N/A   63C    P0   165W / 300W |   7128MiB / 32510MiB |     77%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000000:00:0B.0 Off |                    0 |
| N/A   59C    P0   164W / 300W |  27798MiB / 32510MiB |     77%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000000:00:0C.0 Off |                    0 |
| N/A   53C    P0   139W / 300W |   6834MiB / 32510MiB |     60%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A    533852      C   /usr/bin/python3                 6737MiB |
|    1   N/A  N/A    533853      C   /usr/bin/python3                 7125MiB |
|    2   N/A  N/A    533854      C   /usr/bin/python3                27795MiB |
|    3   N/A  N/A    533855      C   /usr/bin/python3                 6831MiB |
+-----------------------------------------------------------------------------+
```

While my `batch_size` is very small, one of the GPU suddenly takes up much memory during the training process (for example, see the third GPU above), and for many times causes the process to be killed because CUDA out of memory.

An example output of the process is killed:

```
11/14/2021 12:26:37 - INFO - root - Reducer buckets have been rebuilt in this iteration.                                                                                                    
11/14/2021 12:26:37 - INFO - root - Reducer buckets have been rebuilt in this iteration.                                                                                                    
11/14/2021 12:26:37 - INFO - root - Reducer buckets have been rebuilt in this iteration.                                                                                                    
11/14/2021 12:26:37 - INFO - root - Reducer buckets have been rebuilt in this iteration.                                                                                                    
 32%|█████████████████████████████████████████████▊                                                                                                   | 18662/59106 [22:47<47:54, 14.07it/s]
Traceback (most recent call last):                                                                                                                                                          
  File "examples/pytorch/summarization/run_summarization_no_trainer.py", line 619, in <module>                                                                                              
    main()                                                                                                                                                                                  
  File "examples/pytorch/summarization/run_summarization_no_trainer.py", line 538, in main                                                                                                  
    outputs = model(**batch)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl                                                                                        
    return forward_call(*input, **kwargs)                                                     
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 886, in forward                                                                                      
    output = self.module(*inputs[0], **kwargs[0])                                                                                                                                           
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl                                                                                        
    return forward_call(*input, **kwargs)                                                                                                                                                   
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/t5/modeling_t5.py", line 1608, in forward                                                                                
    decoder_outputs = self.decoder(                                                                                                                                                           File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl                                                                                        
    return forward_call(*input, **kwargs)                                                                                                                                                   
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/t5/modeling_t5.py", line 1003, in forward                                                                                
    layer_outputs = layer_module(                                                                                                                                                           
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl                                                                                        
    return forward_call(*input, **kwargs)                                                     
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/t5/modeling_t5.py", line 665, in forward                                                                                 
    cross_attention_outputs = self.layer[1](                                                                                                                                                
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl                                                                                        
    return forward_call(*input, **kwargs)                                                                                                                                                   
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/t5/modeling_t5.py", line 580, in forward                                                                                 
    attention_output = self.EncDecAttention(                                                                                                                                                  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl                                          
    return forward_call(*input, **kwargs)                                                                                                                                                   
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/t5/modeling_t5.py", line 509, in forward                                                                                 
    attn_weights = nn.functional.dropout(                                                                                                                                                   
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py", line 1169, in dropout
    return _VF.dropout_(input, p, training) if inplace else _VF.dropout(input, p, training)   
RuntimeError: CUDA out of memory. Tried to allocate 640.00 MiB (GPU 0; 31.75 GiB total capacity; 28.84 GiB already allocated; 524.00 MiB free; 29.60 GiB reserved in total by PyTorch) If re
served memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF                             
 32%|█████████████████████████████████████████████▊                                                                                                   | 18662/59106 [22:48<49:25, 13.64it/s]
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 506007 closing signal SIGTERM                                                                                         
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 506008 closing signal SIGTERM                                                                                         
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 506009 closing signal SIGTERM                                                                                         
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 506006) of binary: /usr/bin/python3                                                            
Traceback (most recent call last):                                                                                                                                                          
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main                                                                                                                      
    return _run_code(code, main_globals, None,                                                                                                                                              
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code                                                                                                                                 
    exec(code, run_globals)                                                                                                                                                                 
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 193, in <module>                                                                                          
    main()                                                                                                                                                                                  
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 189, in main                                                                                              
    launch(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 174, in launch                                                                                            
    run(args)                                                                                 
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 710, in run                                                                                                  
    elastic_launch(                                                                                                                                                                         
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 131, in __call__                                                                                    
    return launch_agent(self._config, self._entrypoint, list(args))                                                                                                                         
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 259, in launch_agent                                                                                
    raise ChildFailedError(                                                                                                                                                                 torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
```

I am trying to run https://github.com/huggingface/transformers/blob/master/examples/pytorch/summarization/run_summarization_no_trainer.py with the `t5-base` / `t5-small` model. This issue may be related to https://github.com/huggingface/accelerate/issues/96#issuecomment-853829685.

**Comment by sgugger** [comment]
Are you sure there is no interference from another process? I have tried to run the script with `t5-small` and it worked without any spike in any of the GPU.

**Comment by ayaka14732** [comment]
I am sure there is no interference from another process because I own the machine. I have run the script with `t5-small` and `t5-base` for many times, and the GPU usage suddenly increases during training. In fact, I have only successfully completed the training process once so far because of this problem.

**Comment by sgugger** [comment]
Which dataset are you using? One thing that is probably happening then, is that one of the samples of your dataset is significantly longer than the others. On the GPU that treats it (random since the training set is shuffled), you then suddenly get an outburst of memory.

You should adjust the maximum length of your inputs to avoid that.

**Comment by ayaka14732** [comment]
@sgugger Thank you, this is indeed the problem! I am using my custom dataset and one of the sentence is significantly longer 
than others (length > 1000). Adjusting the maximum length fixes this problem.

**Comment by simpleParadox** [comment]
Changing the max length in the tokenizer fixed the issue!
