### ISSUE TITLE
FSDP does not work with mixed precision training

### ISSUE THREAD

**Issue by ChenchaoZhao** [huggingface/accelerate#2009]
### System Info

```Shell
- `Accelerate` version: 0.22.0
- Python version: 3.10.10
- Numpy version: 1.23.5
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 59.85 GB
- GPU type: Tesla V100-SXM2-16GB
```

I could get FSDP working on SageMaker without mixed precision (precision setting to `no`) using the FSDP plug from accelerate. But when I turn on mixed precision (which is supported by the GPU) the FSDP did not work.

I also tried using PyTorch precision setting data class to config the mixed precision but still had no luck.

Is this issue due to integration of Deepspeed + FSDP?

How can we support mixed precision + FSDP in accelerate? I'd love to make a PR if there is a possible solution with changing low level Deepspeed or FSDP codes.
```


### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

```python
fsdp_plugin = FullyShardedDataParallelPlugin(
        state_dict_config=FullStateDictConfig(offload_to_cpu=True, rank0_only=True),
        optim_state_dict_config=FullOptimStateDictConfig(
            offload_to_cpu=True, rank0_only=True
        ),
    )

accelerator = Accelerator(fsdp_plugin=fsdp_plugin, **cfg.accelerator)

# prepare model first
model, lm_head = accelerator.prepare(model, lm_head)
optimizer, train_loader, lr_scheduler = accelerator.prepare(
      optimizer, train_loader, lr_scheduler
  )
```

### Expected behavior

The training will crash if using mixed precision.

**Comment by pacman100** [comment]
Hello, can you try out Accelerate from the main branch to see if the issue has been fixed?

**Comment by ChenchaoZhao** [comment]
It is a PyTorch issue not related to Accelerate. In torch version 2.1 the problem was resolved.

**Comment by varadhbhatnagar** [comment]
@pacman100 I have been using PyTorch FSDP with HF Accelerate and `mixed_precision: 'bf16'` in my accelerate config file. My training doesn't crash even though my PyTorch version is 2.0.1.

Your [blog](https://huggingface.co/blog/pytorch-fsdp) from 2022 says that FSDP with MP didn't work at that time. Do you know in which PyTorch version this issue got fixed?
