### ISSUE TITLE
Accelerator().prepare is too slow 

### ISSUE THREAD

**Issue by WanBenLe** [huggingface/accelerate#2062]
I have a 12GB text data to run these code in 2GPU A40,accelerate==0.23

CUDA_VISIBLE_DEVICES=1,3 accelerate launch --multi_gpu --num_processes=2 --debug ./train.py

print('prepare start')
prepared = accelerator.prepare(*dataloaders, *loss_models, *optimizers)
print('prepare end')

But pass long time I can not see the 'prepare end', Sometimes it showed timeout, Is bug or how can I fix it? Thanks.

### Information
```
E ProcessGroupNCCL.cpp:828 Rank 1 Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1802965 milliseconds before timing out.
Traceback (most recent call last):
  File "/root/autodl-tmp/wsl/专利数据/input/newkeywords/./news.py", line 1079, in <module>
    train_model.fit(train_objectives=[(train_dataloader, train_loss)], epochs=2, warmup_steps=100,accelerator=Accelerator(kwargs_handlers=kwargs), show_progress_bar=True,checkpoint_path='./tmp/',checkpoint_save_steps=2000)
  File "/root/autodl-tmp/wsl/专利数据/input/newkeywords/./news.py", line 750, in fit
    prepared = accelerator.prepare(*dataloaders, *loss_models, *optimizers)
  File "/root/autodl-tmp/conda/envs/wslconda/lib/python3.9/site-packages/accelerate/accelerator.py", line 1284, in prepare
    result = tuple(
  File "/root/autodl-tmp/conda/envs/wslconda/lib/python3.9/site-packages/accelerate/accelerator.py", line 1285, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/root/autodl-tmp/conda/envs/wslconda/lib/python3.9/site-packages/accelerate/accelerator.py", line 1090, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/root/autodl-tmp/conda/envs/wslconda/lib/python3.9/site-packages/accelerate/accelerator.py", line 1429, in prepare_model
    model = torch.nn.parallel.DistributedDataParallel(
  File "/root/autodl-tmp/conda/envs/wslconda/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 674, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/root/autodl-tmp/conda/envs/wslconda/lib/python3.9/site-packages/torch/distributed/utils.py", line 118, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
RuntimeError: DDP expects same model across all ranks, but Rank 1 has 103 params, while rank 0 has inconsistent 0 params.
[E ProcessGroupNCCL.cpp:455] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:460] To avoid data inconsistency, we are taking the entire process down.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 707981 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 1 (pid: 707982) of binary: /root/autodl-tmp/conda/envs/wslconda/bin/python
Traceback (most recent call last):
  File "/root/autodl-tmp/conda/envs/wslconda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/root/autodl-tmp/conda/envs/wslconda/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/root/autodl-tmp/conda/envs/wslconda/lib/python3.9/site-packages/accelerate/commands/launch.py", line 977, in launch_command
    multi_gpu_launcher(args)
  File "/root/autodl-tmp/conda/envs/wslconda/lib/python3.9/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "/root/autodl-tmp/conda/envs/wslconda/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/root/autodl-tmp/conda/envs/wslconda/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/autodl-tmp/conda/envs/wslconda/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
./news.py FAILED
Failures:
  <NO_OTHER_FAILURES>
Root Cause (first observed failure):
[0]:
  time      : 2023-10-18_11:53:27
  host      : autodl-container-86e511a9ae-46ebd236
  rank      : 1 (local_rank: 1)
  exitcode  : -6 (pid: 707982)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 707982
```

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

```python
import os
#os.environ['CUDA_VISIBLE_DEVICES']='1,3'
import pandas as pd
import numpy as np
import gc 
from tqdm import tqdm
import random
seed(42)
import re
import os
from torch.utils.data import DataLoader
from transformers import AutoTokenizer, AutoModel
from sentence_transformers import InputExample, SentencesDataset
from sentence_transformers import  models, losses, SentenceTransformer
from accelerate import Accelerator, DistributedDataParallelKwargs

base_model = models.Transformer(from_s_path)
pooling = models.Pooling(base_model.get_word_embedding_dimension())
train_model = SentenceTransformer(modules=[base_model, pooling])
train_examples = [InputExample(texts=l) for l in texts]
train_dataset = SentencesDataset(train_examples, train_model)
train_dataloader = DataLoader(train_dataset, shuffle=True, batch_size=30)
train_loss = losses.TripletLoss(model=train_model, )

def some_code_with_model_fit():
  n_dataloaders, n_loss_models, n_optimizers = len(dataloaders), len(loss_models), len(optimizers)
  print('start prepare')
  prepared = accelerator.prepare(*dataloaders, *loss_models, *optimizers)
  print('end prepare')
```

### Expected behavior

'end prepare' will show when the prepare  compled

**Comment by BenjaminBossan** [comment]
I think the relevant part of the error message is this one:

> RuntimeError: DDP expects same model across all ranks, but Rank 1 has 103 params, while rank 0 has inconsistent 0 params.

which is not directly related to accelerate.

The only relevant solution I could dig up was [this one](https://discuss.pytorch.org/t/ddp-model-not-synchronizing-across-gpus/175978/5). At the end, it was solved by updating the GPU driver. Could you please test that?

**Comment by muellerzr** [comment]
@WanBenLe you can try using the `DistributedDataParallelKwargs` and pass `find_unused_parameters=True` e.g. `Accelerator(kwarg_handlers=[DistributedDataParallelKwargs(…)])`

**Comment by WanBenLe** [comment]
I used
os.environ['NCCL_DEBUG'] = 'INFO' to show the NCCL hang up, at last, I used os.environ['NCCL_P2P_DISABLE']='1' to sloved this problem
https://github.com/NVIDIA/nccl-tests/issues/117

**Comment by muellerzr** [comment]
@PalaashAgrawal can you open a new issue with a reproducer? I can offer more guidance then :) (As this issue is quite old and closed 6 months ago!)

**Comment by Xnhyacinth** [comment]
> [@muellerzr](https://github.com/muellerzr) Still facing this issue, (seeing an error similar to RuntimeError: DDP expects same model across all ranks, but Rank 1 has `X` params, while rank 0 has inconsistent 0 params, after waiting for >20 mins). Setting the NCCL_P2P_DISABLE flag didn't help, and my CUDA version is quite updated (545.23.08)
> 
> I'm using fast.ai btw. Tried adding kwarg_handlers as well, but i don't think that is the solution. The code is particularly stuck at `model = accelerator.prepare(nn.SyncBatchNorm.convert_sync_batchnorm(model))`, where the model is a very standard transformer model in pytorch
> 
> Is this a widely experienced issue? Have you found a definitive solution for this accelerate.prepare issue?

Have you solved it?
