### ISSUE TITLE
Training hangs, stuck, when using multinode setup with accelerate

### ISSUE THREAD

**Issue by shainisan** [huggingface/accelerate#2144]
Hello,
I have a similar issue to this: https://github.com/huggingface/accelerate/issues/412 but couldn't find a solution.

**Setup**
I'm on google cloud, 2 machines with 1 GPU each. 

**Communication**
I have opened port 11111 on the firewall and verified that I can communicate between the machines like this (two way):
On machine 1: `nc -l 11111`
On machine 2: `echo "Hello from Node 2" | nc ******* 11111`
And it works.

**Accelerate Config**
My config file:
```
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0 # This changes to "1" on the other machine
main_process_ip: ********
main_process_port: 11111
main_training_function: main
mixed_precision: 'no'
num_machines: 2
num_processes: 2
rdzv_backend: nccl
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

**My code:**
```
import torch
import torch.nn as nn
from accelerate import Accelerator

if __name__ == "__main__":
    accelerator = Accelerator()
    print("Loaded accelerator")
    model = nn.Conv2d(10, 20, 3, 1, 1)
    print("Loaded Model")
    model = accelerator.prepare(model)
    print("Accelerator prepared the model")

```
**Debug**

Running the script with: NCCL_DEBUG=INFO accelerate launch test.py

I get this on both machines, and it hangs until NCCL timeout:

Loaded accelerator
Loaded Model
ai-training-base-1:12183:12183 [0] NCCL INFO Bootstrap : Using ens5:10.26.0.4<0>
ai-training-base-1:12183:12183 [0] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin_v6 symbol.
ai-training-base-1:12183:12183 [0] NCCL INFO NET/Plugin: Loaded net plugin FastSocket (v4)
ai-training-base-1:12183:12183 [0] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v6 symbol.
ai-training-base-1:12183:12183 [0] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin symbol (v4 or v5).
ai-training-base-1:12183:12183 [0] NCCL INFO cudaDriverVersion 11080
NCCL version 2.14.3+cuda11.8
ai-training-base-1:12183:12209 [0] NCCL INFO NET/FastSocket : Tx CPU start: -2
ai-training-base-1:12183:12209 [0] NCCL INFO NET/FastSocket : Rx CPU start: -2
ai-training-base-1:12183:12209 [0] NCCL INFO NET/FastSocket : Flow placement enabled.
ai-training-base-1:12183:12209 [0] NCCL INFO NET/FastSocket : queue skip: 0
ai-training-base-1:12183:12209 [0] NCCL INFO NET/FastSocket : Using [0]ens5:10.26.0.4<0>
ai-training-base-1:12183:12209 [0] NCCL INFO NET/FastSocket plugin initialized
ai-training-base-1:12183:12209 [0] NCCL INFO Using network FastSocket

I'd love you help with this. I'm guessing it's a communication issue or NCCL <=> Cuda compatibility issue.

Thanks in advance.

**Comment by muellerzr** [comment]
What happens if you set `same_network` to `False`? (Generally what you should do on the cloud)

**Comment by shainisan** [comment]
Yeah, I tried that too, no change unfortunately. I get the same result and output.

**Comment by shainisan** [comment]
This is how I solved it:

1. I had an older version of NCCL that didn't support CUDA 11.8. For this I've uninstalled and reinstalled Pytorch using pip, which includes a newer version of NCCL.
2. I had to open all the TCP ports in my firewall as NCCL randomly picks ports for communication and doesn't use the main port alone.

**Comment by shainisan** [comment]
This is how I solved it:

1. I had an older version of NCCL that didn't support CUDA 11.8. For this I've uninstalled and reinstalled Pytorch using pip, which includes a newer version of NCCL.
2. I had to open all the TCP ports in my firewall as NCCL randomly picks ports for communication and doesn't use the main port alone.
