### ISSUE TITLE
accelerator.prepare() cuda OOM when equivalent PyTorch code works 

### ISSUE THREAD

**Issue by nnethercott** [huggingface/accelerate#2320]
### System Info

```Shell
`Accelerate` version: 0.25.0
- Platform: Linux-5.10.0-27-cloud-amd64-x86_64-with-glibc2.31
- Python version: 3.10.13
- Numpy version: 1.25.2
- PyTorch version (GPU?): 2.1.0+cu118 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 188.71 GB
- GPU type: NVIDIA L4
- `Accelerate` default config:
	- compute_environment: LOCAL_MACHINE
	- distributed_type: FSDP
	- mixed_precision: fp16
	- use_cpu: False
	- debug: False
	- num_processes: 4
	- machine_rank: 0
	- num_machines: 1
	- rdzv_backend: static
	- same_network: True
	- main_training_function: main
	- fsdp_config: {'fsdp_auto_wrap_policy': 'TRANSFORMER_BASED_WRAP', 'fsdp_backward_prefetch_policy': 'BACKWARD_PRE', 'fsdp_cpu_ram_efficient_loading': True, 'fsdp_forward_prefetch': False, 'fsdp_offload_params': True, 'fsdp_sharding_strategy': 1, 'fsdp_state_dict_type': 'SHARDED_STATE_DICT', 'fsdp_sync_module_states': True, 'fsdp_use_orig_params': False}
	- downcast_bf16: no
	- tpu_use_cluster: False
	- tpu_use_sudo: False
	- tpu_env: []
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

**motivation:** fine tuning [llava-hf/llava-1.5-7b-hf](https://huggingface.co/llava-hf/llava-1.5-7b-hf) with PEFT and accelerate + FSDP

System has more than enough VRAM to fit the model and optimizer as I've done it before but tried switching to training with accelerate after running into issues like huggingface/peft#1142

```bash
>> nvidia-smi

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA L4                      On  | 00000000:00:03.0 Off |                    0 |
| N/A   75C    P0              31W /  72W |      4MiB / 23034MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA L4                      On  | 00000000:00:04.0 Off |                    0 |
| N/A   75C    P0              28W /  72W |      4MiB / 23034MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA L4                      On  | 00000000:00:05.0 Off |                    0 |
| N/A   67C    P0              25W /  72W |      4MiB / 23034MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA L4                      On  | 00000000:00:06.0 Off |                    0 |
| N/A   75C    P0              30W /  72W |      4MiB / 23034MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

```
```python
# main.py 

from transformers import LlavaForConditionalGeneration
from accelerate import Accelerator 
from peft import get_peft_model, LoraConfig 
from accelerate import FullyShardedDataParallelPlugin
from transformers.models.llama.modeling_llama import LlamaDecoderLayer
from transformers.models.clip.modeling_clip import CLIPEncoderLayer
import torch.distributed as dist 

from torch import optim 
import torch 

model_id = "llava-hf/llava-1.5-7b-hf"

# for wrapping FSDP units w/ LoRA (https://github.com/facebookresearch/llama-recipes/blob/38df368a70c292db6e42e0f275139678497fd896/src/llama_recipes/utils/fsdp_utils.py)
def fsdp_auto_wrap_policy(transformer_layer_name):
    import functools
    import os

    from accelerate import FullyShardedDataParallelPlugin
    from torch.distributed.fsdp.wrap import _or_policy, lambda_auto_wrap_policy, transformer_auto_wrap_policy

    from peft.tuners import PrefixEncoder, PromptEmbedding, PromptEncoder

    def lambda_policy_fn(module):
        if (
            len(list(module.named_children())) == 0
            and getattr(module, "weight", None) is not None
            and module.weight.requires_grad
        ):
            return True
        return False

    lambda_policy = functools.partial(lambda_auto_wrap_policy, lambda_fn=lambda_policy_fn)
    transformer_wrap_policy = functools.partial(
        transformer_auto_wrap_policy,
        transformer_layer_cls=(
            PrefixEncoder,
            PromptEncoder,
            PromptEmbedding,
            transformer_layer_name,
        ),
    )

    auto_wrap_policy = functools.partial(_or_policy, policies=[lambda_policy, transformer_wrap_policy])
    return auto_wrap_policy

fsdp_plugin = FullyShardedDataParallelPlugin(
    auto_wrap_policy = fsdp_auto_wrap_policy((LlamaDecoderLayer, CLIPEncoderLayer)),
    #state_dict_config=dist.fsdp.FullStateDictConfig(offload_to_cpu = True), #OOM for saving 
    #optim_state_dict_config=dist.fsdp.ShardedOptimStateDictConfig(offload_to_cpu = True),
)

if __name__ == "__main__":
    accelerator = Accelerator(fsdp_plugin=fsdp_plugin)

    # load llava 
    model = LlavaForConditionalGeneration.from_pretrained(model_id, low_cpu_mem_usage=True, return_dict=True)

    #LoRA config 
    lora_config = LoraConfig(
        r=1,
        target_modules = ["q_proj", "k_proj", "v_proj", "o_proj"],
        lora_alpha = 32, 
        lora_dropout = 0.1,
        bias = "none"
    )
    
    # explicitly enable forward hook 
    # https://discuss.huggingface.co/t/peft-lora-gpt-neox-backward-pass-failing/35641
    # https://github.com/huggingface/peft/issues/1142
    if hasattr(model, "enable_input_require_grads"):
        print("model hasattr `enable_input_requires_grad`")
        model.enable_input_require_grads()
    else:
        def make_inputs_require_grad(module, input, output):
            output.requires_grad_(True)

        model.language_model.get_input_embeddings().register_forward_hook(make_inputs_require_grad)

    model = get_peft_model(model, lora_config)


    optimizer = optim.AdamW(params=model.parameters(), lr=5e-04)
    model, optimizer = accelerator.prepare(model, optimizer)
```

try running with 
```bash
accelerate launch main.py
```

Error:
```bash 
Traceback (most recent call last):
  File "/home/nathaniel/model_playground/llava/hf_training/accelerate_llava_train.py", line 87, in <module>
    model, optimizer = accelerator.prepare(model, optimizer)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/accelerator.py", line 1213, in prepare
    result = tuple(
  File "/opt/conda/lib/python3.10/site-packages/accelerate/accelerator.py", line 1214, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/accelerator.py", line 1094, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/accelerator.py", line 1380, in prepare_model
    model = FSDP(model, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 463, in __init__
    _auto_wrap(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/fsdp/_wrap_utils.py", line 101, in _auto_wrap
    _recursive_wrap(**recursive_wrap_kwargs, **root_kwargs)  # type: ignore[arg-type]
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/fsdp/wrap.py", line 537, in _recursive_wrap
    wrapped_child, num_wrapped_params = _recursive_wrap(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/fsdp/wrap.py", line 537, in _recursive_wrap
    wrapped_child, num_wrapped_params = _recursive_wrap(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/fsdp/wrap.py", line 537, in _recursive_wrap
    wrapped_child, num_wrapped_params = _recursive_wrap(
  [Previous line repeated 3 more times]
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/fsdp/wrap.py", line 555, in _recursive_wrap
    return _wrap(module, wrapper_cls, **kwargs), nonwrapped_numel
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/fsdp/wrap.py", line 484, in _wrap
    return wrapper_cls(module, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 487, in __init__
    _init_param_handle_from_module(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/fsdp/_init_utils.py", line 516, in _init_param_handle_from_module
    _sync_module_params_and_buffers(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/fsdp/_init_utils.py", line 982, in _sync_module_params_and_buffers
    _sync_params_and_buffers(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/utils.py", line 306, in _sync_params_and_buffers
    dist._broadcast_coalesced(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 344.00 MiB. GPU 0 has a total capacty of 21.96 GiB of which 269.81 MiB is free. Including non-PyTorch memory, this process has 21.69 GiB memory in use. Of the allocated memory 21.09 GiB is allocated by PyTorch, and 318.14 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

```
But preparing just the model alone is fine:

```python
# same main.py as above but omitting the `optimizer` init and modifying prepare ... 
model = accelerator.prepare(model)
```

```bash 
>>nvidia-smi

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA L4                      On  | 00000000:00:03.0 Off |                    0 |
| N/A   73C    P0              32W /  72W |   5686MiB / 23034MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA L4                      On  | 00000000:00:04.0 Off |                    0 |
| N/A   76C    P0              37W /  72W |   5686MiB / 23034MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA L4                      On  | 00000000:00:05.0 Off |                    0 |
| N/A   70C    P0              34W /  72W |   5686MiB / 23034MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA L4                      On  | 00000000:00:06.0 Off |                    0 |
| N/A   75C    P0              33W /  72W |   5686MiB / 23034MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A    115959      C   /opt/conda/bin/python3.10                  5674MiB |
|    1   N/A  N/A    115960      C   /opt/conda/bin/python3.10                  5674MiB |
|    2   N/A  N/A    115961      C   /opt/conda/bin/python3.10                  5674MiB |
|    3   N/A  N/A    115962      C   /opt/conda/bin/python3.10                  5674MiB |
+---------------------------------------------------------------------------------------+

```

### Expected behavior

It looks like another case of needing more VRAM but by modifying the [llama-recipes](https://github.com/facebookresearch/llama-recipes) repo using pure PyTorch the model init and optimizer don't blow up the system memory. I also could be missing an argument in the `fsdp_plugin` or misconfigured an aspect of the accelerate config so apologies in advance if this turns out to be something like that.

**Comment by muellerzr** [comment]
cc @pacman100

**Comment by wizyoung** [comment]
Same problem here. Pure pytorch code works fine but accelerate.prepare_model causes the OOM.

**Comment by YiqunChen1999** [comment]
Hi, is the problem solved?

**Comment by marvingabler** [comment]
No, its still a problem

**Comment by antoinedelplace** [comment]
I have a similar problem. Have you found a fix?

**Comment by tengerye** [comment]
Similar problem here.

**Comment by alexpilotti** [comment]
Same issue, using a ESM2-15B model

**Comment by geekpanda-py** [comment]
same

**Comment by jeeyung** [comment]
same

**Comment by ftvalentini** [comment]
SAME!

**Comment by QileSuu** [comment]
Even still a problem now. Using prepare() causes the memory of the model increase to 21G, while loading it without accelerate only costs 7G.
