### ISSUE TITLE
Passing 0 for main_process_port for accelerate does not work

### ISSUE THREAD

**Issue by jayxsinha** [huggingface/accelerate#2955]
### System Info

```Shell
accelerate Version: 0.30.1
torch Version: 2.3.0
transformers Version: 4.41.2
GPU: 2 - A100 80GB SXM

This happens on a Single Node. Both GPUs are on a single node.
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Please review Sweep YAML and Accelerate config yaml to get a look on this. 

### Expected behavior

[accelerate_2_bf16 .txt](https://github.com/user-attachments/files/16356418/accelerate_2_bf16.txt) - Accelerate Config file
[slurm_23908547-4.txt](https://github.com/user-attachments/files/16356422/slurm_23908547-4.txt) - Log from the job
[sweep copy.txt](https://github.com/user-attachments/files/16356430/sweep.copy.txt) - Sweep YAML

As pointed out in the exception: 
ConnectionError: Tried to launch distributed communication on port `29144`, but another process is utilizing it. Please specify a different port (such as using the `--main_process_port` flag or specifying a different `main_process_port` in your config file) and rerun your script. To automatically use the next open port (on a single node), you can set this to `0`.

I set the main_process_port to be 0 but it shows error:
```    tcp_store = TCPStore(hostname, port, world_size, False, timeout)
torch.distributed.DistNetworkError: The client socket has timed out after 600s while trying to connect to (127.0.0.1, 0).
    tcp_store = TCPStore(hostname, port, world_size, False, timeout)
torch.distributed.DistNetworkError: The client socket has timed out after 600s while trying to connect to (127.0.0.1, 0).```

**Comment by abdelkareemkobo** [comment]
@jayxsinha have the same error 
    raise ConnectionError(
ConnectionError: Tried to launch distributed communication on port `29500`, but another process is utilizing it. Please
 specify a different port (such as using the `--main_process_port` flag or specifying a different `main_process_port` i
n your config file) and rerun your script. To automatically use the next open port (on a single node), you can set this
 to `0`.
 trying to run with
 ```python
 accelerate launch .\acc_torch\multi_gpu_accelerate.py --main_process_port 29600
 ``` 
or even make the --main_process_port=0 or equal =29000
but the same error

**Comment by qinchangchang** [comment]
> @jayxsinha有相同的错误 引发ConnectionError（ ConnectionError：试图在端口上启动分布式通信`29500`，但另一个进程正在使用它。请 指定其他端口（例如使用标志或在配置文件中`--main_process_port`指定不同的端口 ）并重新运行脚本。要自动使用下一个开放端口（在单个节点上），您可以将其设置 为。 尝试运行`main_process_port``0`
> 
> ```python
> accelerate launch .\acc_torch\multi_gpu_accelerate.py --main_process_port 29600
> ```
> 
> 甚至使 --main_process_port=0 或等于 =29000 但同样的错误

I encountered the same error. How did you resolve it

**Comment by souravpradhansp** [comment]
Did anyone find a resolution to this issue?

**Comment by jiangzizi** [comment]
Same error

**Comment by SunMarc** [comment]
Can you try with this PR @jiangzizi  ? https://github.com/huggingface/accelerate/pull/3501

**Comment by potpov** [comment]
works for me by specifying the `main_process_port` as an argument with space before the python file:

`accelerate launch --main_process_port 0 main.py --script params`
