### ISSUE TITLE
About Timeout when use Multi-gpu training

### ISSUE THREAD

**Issue by macheng6** [huggingface/accelerate#314]
When I used the single-node multi-GPU mode to train, a timeout error was reported. The strange thing is that for the first few epochs, the code works fine. This error was reported after the end of a step eval in the middle.

The reported error message is：

[E ProcessGroupNCCL.cpp:587] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(OpType=BROADCAST, Timeout(ms)=1800000) ran for 1808499 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:587] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(OpType=BROADCAST, Timeout(ms)=1800000) ran for 1808493 milliseconds before timing out.

[E ProcessGroupNCCL.cpp:341] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.

terminate called after throwing an instance of 'std::runtime_error'
what(): [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(OpType=BROADCAST, Timeout(ms)=1800000) ran for 1808493 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:341] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'

**Comment by sgugger** [comment]
The torch distributed launcher contains a timeout close at 30 minutes that will cancel the processes if met. It seems some instruction in your evaluation loop takes longer than that, which is why you are getting this error. You can increase this timeout by using a `InitProcessGroupKwargs` (see [here](https://github.com/huggingface/accelerate/blob/8595834292b1e7e0543c6d75eb1857da25062b6d/src/accelerate/kwargs_handlers.py#L90) and passing it to the `Accelerator` object under the argument `kwargs_handlers`.

**Comment by macheng6** [comment]
Thanks.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huggingface/accelerate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月12日(星期二) 晚上7:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huggingface/accelerate] About Timeout when use Multi-gpu training (Issue #314)





 
The torch distributed launcher contains a timeout close at 30 minutes that will cancel the processes if met. It seems some instruction in your evaluation loop takes longer than that, which is why you are getting this error. You can increase this timeout by using a InitProcessGroupKwargs (see here and passing it to the Accelerator object under the argument kwargs_handlers.

**Comment by ywdong** [comment]
> > The torch distributed launcher contains a timeout close at 30 minutes that will cancel the processes if met. It seems some instruction in your evaluation loop takes longer than that, which is why you are getting this error. You can increase this timeout by using a `InitProcessGroupKwargs` (see [here](https://github.com/huggingface/accelerate/blob/8595834292b1e7e0543c6d75eb1857da25062b6d/src/accelerate/kwargs_handlers.py#L90) and passing it to the `Accelerator` object under the argument `kwargs_handlers`.
> 
> Hello, I tried to set NCCL_ASYNC_ERROR_HANDLING to 1, but it did not solve the problem. I observed the gpu log and found that the utilization of the two gpus was 100%, and the timeout error was reported after 30 minutes, so the real error may not be caused by timeout. I don't know what caused the gpu utilization to be 100% for the last 30 minutes.

Hi，@macheng6 Did you solve the problem？

**Comment by kowshikthopalli** [comment]
I am running into the same issue. Increasing the time out didnt help. I was utilizing 3 GPUs and and all of them were in 100% utilization for very long. Happens only in the evaluation loop. I am using the following function to calculate accuracy. My class has a featurizer and classifier separately and I have to use `network.module` after doing `accelerator.prepare(network)` because of DistributedDataParallel. 
Thanks a lot for your help. @sgugger @macheng6 
`def accuracy_accelerate_nlp(network, loader, weights, accelerator):
    correct = 0
    total = 0
    network.eval()
    with torch.no_grad():
        predictions=[]
        labels=[]
        for minibatch in loader:
            all_y = minibatch['labels']
            del minibatch['labels']
            outputs = network.module.featurizer(**minibatch, return_dict=True)['pooler_output']
            logits = network.module.classifier(outputs)
            preds= torch.argmax(logits,1)
            predictions.append(accelerator.gather(preds).cpu().numpy())
            labels.append(accelerator.gather(all_y).cpu().numpy())
        predictions = np.concatenate(predictions)
        labels = np.concatenate(labels) 

        predictions = predictions[:len(loader.dataset)]
        labels = labels[:len(loader.dataset)]   
    network.train()

    return accuracy_score(labels,predictions)



`

**Comment by kowshikthopalli** [comment]
Upon further reading I understood that accelerator might be stuck at gather. To avoid this I added
```
preds= accelerator.pad_across_processes(preds)
labels = accelerator.pad_across_processes(labels)
```
before 
```
predictions.append(accelerator.gather(preds).cpu().numpy())
labels.append(accelerator.gather(all_y).cpu().numpy())
```
it is still stuck.

**Comment by macheng6** [comment]
This may not be caused by your code running on cpu or gpu. You can try, use the main process to process data when there are multiple gpus, and it will still report an error for more than 2 hours, so I suspect it is related to the Linux system or implementation of the pytorch.



------------------ Original ------------------
From: Kowshik Thopalli ***@***.***&gt;
Date: Tue,Jul 5,2022 11:36 AM
To: huggingface/accelerate ***@***.***&gt;
Cc: macheng6 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [huggingface/accelerate] About Timeout when use Multi-gputraining (Issue #314)





 
I am running into the same issue. Increasing the time out didnt help. I was utilizing 3 GPUs and and all of them were in 100% utilization for very long. Happens only in the evaluation loop. I am using the following function to calculate accuracy. My class has a featurizer and classifier separately and I have to use network.module after doing accelerator.prepare(network) because of DistributedDataParallel.
 Thanks a lot for your help. @sgugger @macheng6
 `def accuracy_accelerate_nlp(network, loader, weights, accelerator):
 correct = 0
 total = 0
 network.eval()
 with torch.no_grad():
 predictions=[]
 labels=[]
 for minibatch in loader:
 all_y = minibatch['labels']
 del minibatch['labels']
 outputs = network.module.featurizer(**minibatch, return_dict=True)['pooler_output']
 logits = network.module.classifier(outputs)
 preds= torch.argmax(logits,1)
 predictions.append(accelerator.gather(preds).cpu().numpy())
 labels.append(accelerator.gather(all_y).cpu().numpy())
 predictions = np.concatenate(predictions)
 labels = np.concatenate(labels)
     predictions = predictions[:len(loader.dataset)]     labels = labels[:len(loader.dataset)]    network.train() return accuracy_score(labels,predictions)  
`

**Comment by weiyx16** [comment]
Occurred exactly the same problem. This problem happens randomly and doesn't reflect anything informative.

**Comment by Nuwan1654** [comment]
I am having the same issue with yolov7.  https://github.com/WongKinYiu/yolov7/issues/714

**Comment by alexcdot** [comment]
Do you get more useful error messages by setting `TORCH_DISTRIBUTED_DEBUG=INFO` or `NCCL_DEBUG=INFO`?

**Comment by ReedOnePeck** [comment]
> 

Hello, I have encountered the same problem. Have you solved this problem

**Comment by ReedOnePeck** [comment]
> This may not be caused by your code running on cpu or gpu. You can try, use the main process to process data when there are multiple gpus, and it will still report an error for more than 2 hours, so I suspect it is related to the Linux system or implementation of the pytorch.
> […](#)
> ------------------ Original ------------------ From: Kowshik Thopalli ***@***.***&gt; Date: Tue,Jul 5,2022 11:36 AM To: huggingface/accelerate ***@***.***&gt; Cc: macheng6 ***@***.***&gt;, Mention ***@***.***&gt; Subject: Re: [huggingface/accelerate] About Timeout when use Multi-gputraining (Issue #314) I am running into the same issue. Increasing the time out didnt help. I was utilizing 3 GPUs and and all of them were in 100% utilization for very long. Happens only in the evaluation loop. I am using the following function to calculate accuracy. My class has a featurizer and classifier separately and I have to use network.module after doing accelerator.prepare(network) because of DistributedDataParallel. Thanks a lot for your help. @sgugger @macheng6 `def accuracy_accelerate_nlp(network, loader, weights, accelerator): correct = 0 total = 0 network.eval() with torch.no_grad(): predictions=[] labels=[] for minibatch in loader: all_y = minibatch['labels'] del minibatch['labels'] outputs = network.module.featurizer(**minibatch, return_dict=True)['pooler_output'] logits = network.module.classifier(outputs) preds= torch.argmax(logits,1) predictions.append(accelerator.gather(preds).cpu().numpy()) labels.append(accelerator.gather(all_y).cpu().numpy()) predictions = np.concatenate(predictions) labels = np.concatenate(labels) predictions = predictions[:len(loader.dataset)] labels = labels[:len(loader.dataset)] network.train() return accuracy_score(labels,predictions) ` — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

Hello, I have encountered the same problem. Have you solved this problem

**Comment by weiyx16** [comment]
> Do you get more useful error messages by setting environment variables `TORCH_DISTRIBUTED_DEBUG=INFO` or `NCCL_DEBUG=INFO`?

The full log (with NCCL_DEBUG=INFO) is like this:
```
[1,0]<stdout>:[2022-09-27 18:28:44,298][fairseq.trainer][INFO] - begin training epoch 2
[1,0]<stdout>:[2022-09-27 18:28:44,299][fairseq_cli.train][INFO] - Start iterating over samples
[1,0]<stderr>:[E ProcessGroupNCCL.cpp:737] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=22679, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1807330 milliseconds before timing out.
[1,0]<stderr>:[E ProcessGroupNCCL.cpp:414] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
[1,0]<stderr>:terminate called after throwing an instance of 'std::runtime_error'
[1,0]<stderr>:  what():  [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=22679, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1807330 milliseconds before timing out.
[1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 991 closing signal SIGTERM
[1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 992 closing signal SIGTERM
[1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 993 closing signal SIGTERM
[1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 994 closing signal SIGTERM
[1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 995 closing signal SIGTERM
[1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 996 closing signal SIGTERM
[1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 998 closing signal SIGTERM
[1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1000 closing signal SIGTERM
[1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1002 closing signal SIGTERM
[1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1004 closing signal SIGTERM
[1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1005 closing signal SIGTERM
[1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1008 closing signal SIGTERM
[1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1010 closing signal SIGTERM
[1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1012 closing signal SIGTERM
[1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1014 closing signal SIGTERM
[1,0]<stderr>:ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 990) of binary: /opt/conda/bin/python
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
```
Also actually I'm using fairest but not huggingface, but I think this maybe a share issue between them. I will try to set TORCH_DISTRIBUTED_DEBUG=INFO and see whether we can get more.

**Comment by Nuwan1654** [comment]
I had the same issue with yolov7, by incteasing the time out from 30 min to 1.5h solved it.
`dist.init_process_group(backend='nccl', init_method='env://', timeout=datetime.timedelta(seconds=5400)) `

**Comment by ReedOnePeck** [comment]
> > Do you get more useful error messages by setting environment variables `TORCH_DISTRIBUTED_DEBUG=INFO` or `NCCL_DEBUG=INFO`?
> 
> The full log (with NCCL_DEBUG=INFO) is like this:
> 
> ```
> [1,0]<stdout>:[2022-09-27 18:28:44,298][fairseq.trainer][INFO] - begin training epoch 2
> [1,0]<stdout>:[2022-09-27 18:28:44,299][fairseq_cli.train][INFO] - Start iterating over samples
> [1,0]<stderr>:[E ProcessGroupNCCL.cpp:737] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=22679, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1807330 milliseconds before timing out.
> [1,0]<stderr>:[E ProcessGroupNCCL.cpp:414] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
> [1,0]<stderr>:terminate called after throwing an instance of 'std::runtime_error'
> [1,0]<stderr>:  what():  [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=22679, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1807330 milliseconds before timing out.
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 991 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 992 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 993 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 994 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 995 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 996 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 998 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1000 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1002 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1004 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1005 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1008 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1010 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1012 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1014 closing signal SIGTERM
> [1,0]<stderr>:ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 990) of binary: /opt/conda/bin/python
> [1,0]<stderr>:Traceback (most recent call last):
> [1,0]<stderr>:  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
> ```
> 
> Also actually I'm using fairest but not huggingface, but I think this maybe a share issue between them. I will try to set TORCH_DISTRIBUTED_DEBUG=INFO and see whether we can get more. By the way, I always reach this problem at the beginning of a new epoch...


Actually, I didn't use huggingface, but I reached this problem at the beginning of a new epoch too, I will try to increase the time out from 30min to 120min.

**Comment by ReedOnePeck** [comment]
> I had the same issue with yolov7, by incteasing the time out from 30 min to 1.5h solved it. `dist.init_process_group(backend='nccl', init_method='env://', timeout=datetime.timedelta(seconds=5400)) `

 Thank you very much, I will try it.

**Comment by TheBloodthirster** [comment]
> I had the same issue with yolov7, by incteasing the time out from 30 min to 1.5h solved it. `dist.init_process_group(backend='nccl', init_method='env://', timeout=datetime.timedelta(seconds=5400)) `

I'm have a example for this question which I was reading 200G file to generate every line offset and need to use 1 hour 30 min: 

Error : 
<class 'data.read_data.LineShuffler'>: Init /vc_data/users/junpenghuang/trigger_model_data/0711-0814/NegativeTrain                                                             
 35%|████████████████████████████████████████                                                                         | 73811210851/208140108456 [30:01<57:14, 39115047.81MB/s]
[E ProcessGroupNCCL.cpp:485] [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1802246 milliseconds before timing 
out.                                                                                                                                                                           
[E ProcessGroupNCCL.cpp:485] [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1802251 milliseconds before timing 
out.                                                                                                                                                                           
[E ProcessGroupNCCL.cpp:485] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1802264 milliseconds before timing 
out.                                                                                                                                                                           
[E ProcessGroupNCCL.cpp:485] [Rank 5] Watchdog caught collective operation timeout: WorkNCCL(OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1802265 milliseconds before timing 
out.                                                                                                                                                                           
 35%|████████████████████████████████████████                                                                         | 73823245538/208140108456 [30:02<56:12, 39826072.37MB/s]
Traceback (most recent call last):

**Comment by weiyx16** [comment]
> > Do you get more useful error messages by setting environment variables `TORCH_DISTRIBUTED_DEBUG=INFO` or `NCCL_DEBUG=INFO`?
> 
> The full log (with NCCL_DEBUG=INFO) is like this:
> 
> ```
> [1,0]<stdout>:[2022-09-27 18:28:44,298][fairseq.trainer][INFO] - begin training epoch 2
> [1,0]<stdout>:[2022-09-27 18:28:44,299][fairseq_cli.train][INFO] - Start iterating over samples
> [1,0]<stderr>:[E ProcessGroupNCCL.cpp:737] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=22679, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1807330 milliseconds before timing out.
> [1,0]<stderr>:[E ProcessGroupNCCL.cpp:414] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
> [1,0]<stderr>:terminate called after throwing an instance of 'std::runtime_error'
> [1,0]<stderr>:  what():  [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=22679, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1807330 milliseconds before timing out.
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 991 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 992 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 993 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 994 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 995 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 996 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 998 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1000 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1002 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1004 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1005 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1008 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1010 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1012 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1014 closing signal SIGTERM
> [1,0]<stderr>:ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 990) of binary: /opt/conda/bin/python
> [1,0]<stderr>:Traceback (most recent call last):
> [1,0]<stderr>:  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
> ```
> 
> Also actually I'm using fairest but not huggingface, but I think this maybe a share issue between them. I will try to set TORCH_DISTRIBUTED_DEBUG=INFO and see whether we can get more. By the way, I always reach this problem at the beginning of a new epoch...

The reason for my case is that the rank0 saved checkpoint to a remote storage space for a long time, and fairseq doesn't include any ```torch.barrier()``` in function of saving checkpoint. The other ranks went into forward and backward immediately, while the rank0 was still saving checkpoint. Due to this, the other ranks were waiting for rank0 to do ```all_reduce``` and finally the nccl ops were time out.

**Comment by gcunhase** [comment]
@weiyx16 did you find a solution for this issue?

**Comment by shizhediao** [comment]
same question

**Comment by shizhediao** [comment]
> I had the same issue with yolov7, by incteasing the time out from 30 min to 1.5h solved it. `dist.init_process_group(backend='nccl', init_method='env://', timeout=datetime.timedelta(seconds=5400)) `

I tried this one and solved it. Thanks!

**Comment by derekchen14** [comment]
The timeout solution leads to

 ```INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:2 to store for rank: 1
Traceback (most recent call last):
  File "main.py", line 255, in <module>
    run_prompt_train(args, model, datasets, exp_logger, ontology)
  File "main.py", line 222, in run_prompt_train
    torch.distributed.init_process_group(backend='nccl', init_method='env://',
  File "/home/paperspace/.local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 544, in init_process_group
    raise RuntimeError("trying to initialize the default process group " "twice!")
RuntimeError: trying to initialize the default process group twice!
```

But even in the case that it works, it seems that just waiting around for 1.5 hours doesn't seem right.  Is there some rank 0 process that should be terminated or stopped earlier to prevent the delay from occurring in the first place?

**Comment by weiyx16** [comment]
> @weiyx16 did you find a solution for this issue?

I just saved the checkpoint locally to avoid it. You can also add a `torch.barrier()` to sync each process after model saving.

**Comment by Greyer** [comment]
use model.module(input) to eval rather than model(input), i solve the problem this way, thanks @kowshikthopalli !

**Comment by weiddeng** [comment]
Hi Greyer, I tried your method but still not worky..

**Comment by lengmo1996** [comment]
> Hi Greyer, I tried your method but still not worky..

I have the same error. (but it works well in 2GPUs and occurred in 4GPUs)When I set NCCL_DEBUG=INFO, the output said, "Could not enable P2P between dev 2(=d5000) and dev 1(=d1000) ...". So, I set the environment variable NCCL_P2P_DISABLE=1, this solved my problem. I hope this information is helpful to you.

**Comment by weiddeng** [comment]
yeah yeah yeah, lengmo1996 you are exactly right!
Thank you so much, really appreciated!

> > Hi Greyer, I tried your method but still not worky..
> 
> I have the same error(but it works well in 2GPUs and occurred in 4GPUs). When I set NCCL_DEBUG=INFO, the output said, "Could not enable P2P between dev 2(=d5000) and dev 1(=d1000) ...". So, I set the environment variable NCCL_P2P_DISABLE=1, this solved my problem. I hope this information is helpful to you.

**Comment by lengmo1996** [comment]
> yeah yeah yeah, lengmo1996 you are exactly right! Thank you so much, really appreciated!
> 
> > > Hi Greyer, I tried your method but still not worky..
> > 
> > 
> > I have the same error(but it works well in 2GPUs and occurred in 4GPUs). When I set NCCL_DEBUG=INFO, the output said, "Could not enable P2P between dev 2(=d5000) and dev 1(=d1000) ...". So, I set the environment variable NCCL_P2P_DISABLE=1, this solved my problem. I hope this information is helpful to you.

I'm glad my information can help you. I have found this error reproduced in some special cases, such as some code only running in the local process or main process. If the running time is larger than the setting of timed out in DDP (Pytorch) or Accelerator (hugginface), the Watchdog will shut down the whole code and report the same error. In these cases, we need to modify our code to avoid this problem.

**Comment by PeiwenSun2000** [comment]
> The torch distributed launcher contains a timeout close at 30 minutes that will cancel the processes if met. It seems some instruction in your evaluation loop takes longer than that, which is why you are getting this error. You can increase this timeout by using a `InitProcessGroupKwargs` (see [here](https://github.com/huggingface/accelerate/blob/8595834292b1e7e0543c6d75eb1857da25062b6d/src/accelerate/kwargs_handlers.py#L90) and passing it to the `Accelerator` object under the argument `kwargs_handlers`.

This method does not solve the problem in my case. Even though I set 300 minutes, still, get the error for a timeout of 30 minutes.

**Comment by bestpredicts** [comment]
same error 

> > The torch distributed launcher contains a timeout close at 30 minutes that will cancel the processes if met. It seems some instruction in your evaluation loop takes longer than that, which is why you are getting this error. You can increase this timeout by using a `InitProcessGroupKwargs` (see [here](https://github.com/huggingface/accelerate/blob/8595834292b1e7e0543c6d75eb1857da25062b6d/src/accelerate/kwargs_handlers.py#L90) and passing it to the `Accelerator` object under the argument `kwargs_handlers`.
> 
> This method does not solve the problem in my case. Even though I set 300 minutes, still, get the error for a timeout of 30 minutes.
same here  , any update? @sgugger

**Comment by iseesaw** [comment]
It works well after I set `export NCCL_P2P_LEVEL=NVL`

**Comment by murphypei** [comment]
I had the same problem when using streaming dataset, but none of the above mentioned solved it. It seems it's a bug of accelerate.

**Comment by densechen** [comment]
I also face the same problem but still failed after trying all mentioned methods....

**Comment by DrrJia** [comment]
I found one reason from internet, that is the IO virtualization issue. One can set export NCCL_P2P_DISABLE=1 before executing the code. Please refer to the webpage https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html#gpu-direct

**Comment by czas09** [comment]
> I found one reason from internet, that is the IO virtualization issue. One can set export NCCL_P2P_DISABLE=1 before executing the code. Please refer to the webpage https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html#gpu-direct

Thank you DrrJia! Your method solves the problem on my machine :thumbsup:

**Comment by DhruvaBansal00** [comment]
@DrrJia could you tell me a bit about which machine/setup you are using and seeing this error on? I am seeing the same on a cloud VM.

**Comment by DrrJia** [comment]
> @DrrJia could you tell me a bit about which machine/setup you are using and seeing this error on? I am seeing the same on a cloud VM.

server ubuntu system

**Comment by sakshidotvakilsearch** [comment]
@sgugger & everyone. I encountered this issue when I tried to run evaluation on validation data (medium-sized). The issue seemed to be more of a discrepancy where one process was doing an operation that the other process could not serve for & all of them were not at the same point in the flow. My code flow looked like this

```mermaid
graph TD
    main-->load_peft_config-->peft_config
    main-->load_og_model-->og_model
    peft_config-->peft_model
    og_model-->peft_model
    main-->load_tokenizer-->tokenizer
    peft_model-->create_dataset
    tokenizer-->create_dataset
    create_dataset-->load_dataset_hf_datasets-->hf_dataset
    hf_dataset--> clean_data_with_main_process_first
    clean_data_with_main_process_first-->tokenize_with_main_process_first
    tokenize_with_main_process_first-->group_text_with_main_process_first
    group_text_with_main_process_first-->return_dataset
    return_dataset-->dataloaders
    dataloaders-->accelerator.prepare
    peft_model-->accelerator.prepare
    accelerator.prepare-->accelerator_prepared_model
    accelerator.prepare-->accelerator_prepared_dataloaders
    accelerator_prepared_model-->evaluate
    accelerator_prepared_dataloaders-->evaluate
```

In the above flow, the error was arising because some processes were tokenising & grouping text or were stuck in the previous operations while some were evaluating and thus performing the `all_gather` or `all_reduce` operations. I had assumed that accelerator was taking care of the dataset preparation & other operations being synced across processes with to `with accelerator.main_process_first()` which was used while cleaning, tokenising & grouping functions were called. But maybe that was not happening efficiently or I don't know. So I added the call for `accelerator.wait_for_everyone()` after my `create_dataset()` function returned datasets & prepared the dataloaders. This resolved the issue since now all processes have definitely finished preparing the dataloader before starting evaluation. Maybe when I scale beyond this dataset size further, it might take even longer or fail and the nccl timeout maybe the issue, but this was my fix for this error for a medium sized dataset.

**Comment by kinredon** [comment]
> > Do you get more useful error messages by setting environment variables `TORCH_DISTRIBUTED_DEBUG=INFO` or `NCCL_DEBUG=INFO`?
> 
> The full log (with NCCL_DEBUG=INFO) is like this:
> 
> ```
> [1,0]<stdout>:[2022-09-27 18:28:44,298][fairseq.trainer][INFO] - begin training epoch 2
> [1,0]<stdout>:[2022-09-27 18:28:44,299][fairseq_cli.train][INFO] - Start iterating over samples
> [1,0]<stderr>:[E ProcessGroupNCCL.cpp:737] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=22679, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1807330 milliseconds before timing out.
> [1,0]<stderr>:[E ProcessGroupNCCL.cpp:414] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
> [1,0]<stderr>:terminate called after throwing an instance of 'std::runtime_error'
> [1,0]<stderr>:  what():  [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=22679, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1807330 milliseconds before timing out.
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 991 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 992 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 993 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 994 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 995 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 996 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 998 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1000 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1002 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1004 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1005 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1008 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1010 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1012 closing signal SIGTERM
> [1,0]<stderr>:WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1014 closing signal SIGTERM
> [1,0]<stderr>:ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 990) of binary: /opt/conda/bin/python
> [1,0]<stderr>:Traceback (most recent call last):
> [1,0]<stderr>:  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
> ```
> 
> Also actually I'm using fairest but not huggingface, but I think this maybe a share issue between them. I will try to set TORCH_DISTRIBUTED_DEBUG=INFO and see whether we can get more. By the way, I always reach this problem at the beginning of a new epoch...

I met the same problem, which occurs at the beginning of a new epoch.

**Comment by shainisan** [comment]
**This solves the issue:**

```
from datetime import timedelta
from accelerate import InitProcessGroupKwargs

# Create the custom configuration
process_group_kwargs = InitProcessGroupKwargs(timeout=timedelta(seconds=5400))  # 1.5 hours

# Instantiate Accelerator with the custom configuration
accelerator = Accelerator(kwargs_handlers=[process_group_kwargs])
```

**Comment by akeyhero** [comment]
In my case, I got this error due to `accelerator.main_process_first()`.

```py
with accelerator.main_process_first():
    model = AutoModelForCausalLM.from_pretrained('...')
```

With `zero3_init_flag: true`, this code should be rewritten as:

```py
with accelerator.main_process_first():
    with deepspeed.zero.init():
        model = AutoModelForCausalLM.from_pretrained('...')
```

In my theory, `deepspeed.zero.init()` pauses until all processes reach this point, whereas `accelerator.main_process_first()` blocks all non-main processes, preventing them from getting there.

**Comment by akeyhero** [comment]
I encountered this error again when attempting to save my model to a network disk.
I seemed to resolve this problem by first saving the model to the local disk and then transferring it to the network disk using `subprocess.Popen` and the `rsync` command.

**Comment by thelongestusernameofall** [comment]
solution in https://github.com/NVIDIA/nccl/issues/426 works.

export NCCL_IB_GID_INDEX=3 solved my problem.

**Comment by jedyang97** [comment]
Hi just providing some additional insights. For me, I encountered this exact same issue when training an adapted version of Llama-7B on multiple GPUs using Huggingface Transformers Trainer. The training epochs were fine and the error (deadlock then times out) only happened during eval after a few eval steps. I tried all of the suggested remedies but had no luck. Eventually what solved my problem was to set `prediction_loss_only=True` for the Trainer. I believe the `labels` returned in `evaluation_loop()` in Trainer was causing some weird deadlock when the accumulated `all_labels` tensor grew too large. Setting prediction_loss_only=True`  prevents the `prediction_step()` from returning any labels and thus circumvents this problem. Hope this could help someone who's struggling; meaning while it would be great if this could be further root-caused. @sgugger

**Comment by wangguojim** [comment]
This issue is caused by the accelerator caching data, which occupies a large amount of memory and leads to crashes. Clearing the cache should help.

**Comment by getao** [comment]
> This issue is caused by the accelerator caching data, which occupies a large amount of memory and leads to crashes. Clearing the cache should help.

Any instruction to clean up the cache? I used the streaming dataloader and it seems not to produce cache for the dataset.

**Comment by wangguojim** [comment]
已收到

**Comment by yuleiqin** [comment]
I am facing the same issue; and the process just stops at step 21 consistently; I can reproduce the results with the fixed seed.....I dont know what happens; I am training MoE models with deepspeed Zero3 and huggingface transformer

**Comment by dctanner** [comment]
I'm on an 8x 3090 Supermicro system.

I was on driver version 545 and had the bug unless I set NCCL_P2P_DISABLE=1.

Downgrading to 535 makes things work without having to set NCCL_P2P_DISABLE=1

**Comment by wangguojim** [comment]
已收到

**Comment by heichang12138** [comment]
> I'm on an 8x 3090 Supermicro system.
> 
> I was on driver version 545 and had the bug unless I set NCCL_P2P_DISABLE=1.
> 
> Downgrading to 535 makes things work without having to set NCCL_P2P_DISABLE=1

set NCCL_P2P_DISABLE=1 works for me! Although my driver is 535.104.05

**Comment by NanYANG2015** [comment]
Has this problem been resolved? I encountered the same problem.
It always appears at the beginning of the evaluation, resume_from_checkpoint, then training continues normally (seed remains unchanged, ignore_data_skip=False).
[E ProcessGroupNCCL.cpp:474] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3370, OpType=_ALLGATHER_BASE, NumelIn=8, NumelOut=320, Timeout(ms)=1800000) ran for 1800251 milliseconds before timing out .
Or [E ProcessGroupGloo.cpp:2810] [Rank 0]: Rank 24 failed to pass monitoredBarrier in 1800000 ms
I use pytorch 2.1.0 + transformers 4.32.0 + Deepspeed 0.13.1 Zero1, docker image is nvidia/cuda:12.2.2-cudnn8-devel-ubuntu22.04, inter-node communication uses IB

**Comment by gigadawn** [comment]
> > Hi Greyer, I tried your method but still not worky..
> 
> I have the same error(but it works well in 2GPUs and occurred in 4GPUs). When I set NCCL_DEBUG=INFO, the output said, "Could not enable P2P between dev 2(=d5000) and dev 1(=d1000) ...". So, I set the environment variable NCCL_P2P_DISABLE=1, this solved my problem. I hope this information is helpful to you.

I solved this problem using this method!

**Comment by wangguojim** [comment]
已收到

**Comment by YeeShih** [comment]
Have a try: export NCCL_P2P_DISABLE=0 and export NCCL_P2P_LEVEL=NVL

**Comment by wangguojim** [comment]
已收到

**Comment by HH-LG** [comment]
> I am facing the same issue; and the process just stops at step 21 consistently; I can reproduce the results with the fixed seed.....I dont know what happens; I am training MoE models with deepspeed Zero3 and huggingface transformer

Hello, my condition is exactly the same as yours, that is, crash after some fixed step using a fixed seed, no matter what the input data is. Have you solve the problem?

**Comment by wangguojim** [comment]
已收到
