### ISSUE TITLE
fsdp checkpoint saving leads to NCCL WARN Cuda failure 2 'out of memory'

### ISSUE THREAD

**Issue by edchengg** [huggingface/accelerate#3232]
### System Info

```Shell
accelerate                1.0.1   
torch                     2.4.0
python                    3.10.14
transformers              4.45.2

FullyShardedDataParallelPlugin(sharding_strategy=<ShardingStrategy.FULL_SHARD: 1>, backward_prefetch=None, mixed_precision_policy=MixedPrecision(param_dtype=torch.bfloat16, reduce_dtype=torch.bfloat16, buffer_dtype=torch.bfloat16, keep_low_precision_grads=False, cast_forward_inputs=False, cast_root_forward_inputs=True, _module_classes_to_ignore=(<class 'torch.nn.modules.batchnorm._BatchNorm'>,)), auto_wrap_policy=<function transformer_auto_wrap_policy at 0x155486506050>, cpu_offload=CPUOffload(offload_params=False), ignored_modules=None, state_dict_type=<StateDictType.SHARDED_STATE_DICT: 3>, state_dict_config=ShardedStateDictConfig(offload_to_cpu=True, _use_dtensor=False), optim_state_dict_config=ShardedOptimStateDictConfig(offload_to_cpu=True, _use_dtensor=False), limit_all_gathers=True, use_orig_params=True, param_init_fn=<function FullyShardedDataParallelPlugin.__post_init__.<locals>.<lambda> at 0x155230e00ee0>, sync_module_states=True, forward_prefetch=False, activation_checkpointing=True, cpu_ram_efficient_loading=True, transformer_cls_names_to_wrap=['Qwen2DecoderLayer'], min_num_params=None)
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

when I use FSDP to train a model on 16-32 node cluster. Sometime it hit this error "NCCL WARN Cuda failure 2 'out of memory'" when save the model checkpoint. resulting in an empty folder.
sometimes it works fine. Anyone had similar experience before? This really puzzles me as i already use offload_to_cpu = True for SHARDED_STATE_DICT

```

Traceback (most recent call last):
[rank150]:   File "/finetune_orm_bt_listwise_fsdp.py", line 353, in <module>
[rank150]:     trainer.train(resume_from_checkpoint=script_args.resume_from_checkpoint)
[rank150]:   File "lib/python3.10/site-packages/transformers/trainer.py", line 2052, in train
[rank150]:     return inner_training_loop(
[rank150]:   File "lib/python3.10/site-packages/transformers/trainer.py", line 2467, in _inner_training_loop
[rank150]:     self._maybe_log_save_evaluate(tr_loss, grad_norm, model, trial, epoch, ignore_keys_for_eval)
[rank150]:   File "lib/python3.10/site-packages/transformers/trainer.py", line 2918, in _maybe_log_save_evaluate
[rank150]:     self._save_checkpoint(model, trial, metrics=metrics)
[rank150]:   File "lib/python3.10/site-packages/transformers/trainer.py", line 3012, in _save_checkpoint
[rank150]:     self._save_optimizer_and_scheduler(output_dir)
[rank150]:   File "lib/python3.10/site-packages/transformers/trainer.py", line 3147, in _save_optimizer_and_scheduler
[rank150]:     save_fsdp_model(
[rank150]:   File "lib/python3.10/site-packages/accelerate/utils/fsdp_utils.py", line 107, in save_fsdp_model
[rank150]:     dist_cp.save_state_dict(
[rank150]:   File "lib/python3.10/site-packages/typing_extensions.py", line 2853, in wrapper
[rank150]:     return arg(*args, **kwargs)
[rank150]:   File "lib/python3.10/site-packages/torch/distributed/checkpoint/state_dict_saver.py", line 47, in save_state_dict
[rank150]:     return _save_state_dict(
[rank150]:   File "lib/python3.10/site-packages/torch/distributed/checkpoint/state_dict_saver.py", line 316, in _save_state_dict
[rank150]:     central_plan: SavePlan = distW.reduce_scatter("plan", local_step, global_step)
[rank150]:   File "lib/python3.10/site-packages/torch/distributed/checkpoint/utils.py", line 190, in reduce_scatter
[rank150]:     result = self.scatter_object(all_results)
[rank150]:   File "lib/python3.10/site-packages/torch/distributed/checkpoint/utils.py", line 135, in scatter_object
[rank150]:     dist.scatter_object_list(
[rank150]:   File "lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
[rank150]:     return func(*args, **kwargs)
[rank150]:   File "lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3019, in scatter_object_list
[rank150]:     scatter(
[rank150]:   File "lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
[rank150]:     return func(*args, **kwargs)
[rank150]:   File `"lib/python3.10/site-packages/torch/distributed/distributed_c10d.py",` line 3480, in scatter
[rank150]:     work = default_pg.scatter(output_tensors, input_tensors, opts)
[rank150]: RuntimeError: NCCL Error 1: unhandled cuda error (run with NCCL_DEBUG=INFO for details)
```

### Expected behavior

save the ckpt fine

**Comment by cchenv** [comment]
Hi @edchengg did you fix it? I met a similar problem and setting `fsdp_state_dict_type` to `FULL_STATE_DICT` (instead of the recommended `SHARDED_STATE_DICT`) works.

**Comment by edchengg** [comment]
> Hi @edchengg did you fix it? I met a similar problem and setting `fsdp_state_dict_type` to `FULL_STATE_DICT` (instead of the recommended `SHARDED_STATE_DICT`) works.

Hi, thanks for following up.
I ended up downgrade the accelerate version to an older version and then it works fine.

**Comment by lijing1996** [comment]
> > Hi [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/20430102?s=64&amp;v=4">@edchengg](https://github.com/edchengg) did you fix it? I met a similar problem and setting `fsdp_state_dict_type` to `FULL_STATE_DICT` (instead of the recommended `SHARDED_STATE_DICT`) works.
> 
> Hi, thanks for following up. I ended up downgrade the accelerate version to an older version and then it works fine.

Could you tell me which old version do you use? Thank you.

**Comment by edchengg** [comment]
> > > Hi [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/20430102?s=64&amp;v=4">@edchengg](https://github.com/edchengg) did you fix it? I met a similar problem and setting `fsdp_state_dict_type` to `FULL_STATE_DICT` (instead of the recommended `SHARDED_STATE_DICT`) works.
> > 
> > 
> > Hi, thanks for following up. I ended up downgrade the accelerate version to an older version and then it works fine.
> 
> Could you tell me which old version do you use? Thank you.

I ended up use the accelerate==0.34.0
