### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!

### ISSUE THREAD

**Issue by Indigo-Coder-github** [huggingface/accelerate#3612]
### System Info

```Shell
accelerate env


- `Accelerate` version: 1.7.0
- Platform: Linux-5.15.0-130-generic-x86_64-with-glibc2.35
- `accelerate` bash location: /usr/local/bin/accelerate
- Python version: 3.10.12
- Numpy version: 1.26.4
- PyTorch version: 2.7.0+cu126
- PyTorch accelerator: CUDA
- System RAM: 251.63 GB
- GPU type: NVIDIA L40S
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: no
        - use_cpu: False
        - debug: False
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - rdzv_backend: static
        - same_network: False
        - main_training_function: main
        - enable_cpu_affinity: False
        - downcast_bf16: False
        - tpu_use_cluster: False
        - tpu_use_sudo: False
```

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [x] My own task or dataset (give details below)

### Reproduction

Python 3.10 & the version of my libraries
```bash
torch 2.7.0
datasets 3.2.0
peft 0.14.0
transformers 4.52.4
trl 0.13.0
bitsandbytes 0.46.0
```
I want to fine tuning Llama 3.3 70B with QLoRA on L40S * 2 (48GB * 2). So I wrote below code.

```python
import os
import torch
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
)
from peft import LoraConfig
from trl import SFTTrainer, SFTConfig
from datasets import load_dataset

def main():
    model_id = "meta-llama/Llama-3.3-70B-Instruct"
    
    quantization_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_use_double_quant=True,
    )

    lora_config = LoraConfig(
        r=16,
        lora_alpha=32,
        target_modules=["q_proj", "v_proj"],
        task_type="CAUSAL_LM",
    )

    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        device_map="auto",
        quantization_config=quantization_config,
        torch_dtype=torch.bfloat16,
        low_cpu_mem_usage=True,
    )
    
    tokenizer = AutoTokenizer.from_pretrained(model_id, add_eos_token=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
        
    model.config.pad_token_id = tokenizer.pad_token_id
    
    train_dataset = load_dataset("ChuGyouk/Asan-AMC-Healthinfo", split="train")

    def chat_template(example):
        example["text"] = tokenizer.apply_chat_template(
            [
                {"role": "user", "content": example['instruction']},
                {"role": "assistant", "content": example['output']},
            ],
            tokenize=False,
        )
        return example

    train_dataset = train_dataset.map(chat_template)

    sft_config = SFTConfig(
        output_dir="./fine_tuned/Llama-3.3-70B-Script-Test",
        overwrite_output_dir=True,
        do_train=True,
        max_seq_length=64,
        per_device_train_batch_size=1,
        gradient_accumulation_steps=8,
        num_train_epochs=1,
        dataset_text_field="text",
        bf16=True,
    )

    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        args=sft_config,
        peft_config=lora_config,
        train_dataset=train_dataset,
    )

    print(f"--- [Process {os.getpid()}, Rank {trainer.accelerator.process_index}] 학습 시작 ---")
    trainer.train()
    print(f"--- [Process {os.getpid()}, Rank {trainer.accelerator.process_index}] 학습 완료 ---")

if __name__ == "__main__":
    main()
```

When I run `accelerate launch gpu_test.py`, the code can't recognize multi gpus and result in CUDA OOM.
```bash
Loading checkpoint shards:  37%|████████████████████████████████▎                                                       | 11/30 [00:09<00:17,  1.11it/s]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/A.I_DATA/jbnu/joonseo/gpu_test.py", line 83, in <module>
[rank0]:     main()
[rank0]:   File "/A.I_DATA/jbnu/joonseo/gpu_test.py", line 30, in main
[rank0]:     model = AutoModelForCausalLM.from_pretrained(
[rank0]:   File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 571, in from_pretrained
[rank0]:     return model_class.from_pretrained(
[rank0]:   File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 309, in _wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4574, in from_pretrained
[rank0]:     ) = cls._load_pretrained_model(
[rank0]:   File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 5031, in _load_pretrained_model
[rank0]:     disk_offload_index, cpu_offload_index = _load_state_dict_into_meta_model(
[rank0]:   File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 795, in _load_state_dict_into_meta_model
[rank0]:     shard_and_distribute_module(
[rank0]:   File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/transformers/integrations/tensor_parallel.py", line 911, in shard_and_distribute_module
[rank0]:     param = tp_layer.partition_tensor(
[rank0]:   File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/transformers/integrations/tensor_parallel.py", line 575, in partition_tensor
[rank0]:     parameter = parameter.contiguous()
[rank0]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 224.00 MiB. GPU 0 has a total capacity of 44.39 GiB of which 87.06 MiB is free. Process 4068106 has 724.00 MiB memory in use. Including non-PyTorch memory, this process has 43.59 GiB memory in use. Of the allocated memory 43.08 GiB is allocated by PyTorch, and 25.02 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[rank0]:[W607 15:17:07.206945885 ProcessGroupNCCL.cpp:1476] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
W0607 15:17:08.246000 4071006 torch/distributed/elastic/multiprocessing/api.py:900] Sending process 4071140 closing signal SIGTERM
E0607 15:17:08.361000 4071006 torch/distributed/elastic/multiprocessing/api.py:874] failed (exitcode: 1) local_rank: 0 (pid: 4071139) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 50, in main
    args.func(args)
  File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1189, in launch_command
    multi_gpu_launcher(args)
  File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 815, in multi_gpu_launcher
    distrib_run.run(args)
  File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 270, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
gpu_test.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-06-07_15:17:08
  host      : humanai.chonbuk.ac.kr
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 4071139)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

When I run `python3.10 gpu_test.py`, the code recognize multi gpus. But distribution doesn't work.
```bash
[2025-06-07 15:18:18,752] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
--- [Process 4071205, Rank 0] 학습 시작 ---
  0%|                                                                                                                          | 0/2395 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/A.I_DATA/jbnu/joonseo/gpu_test.py", line 82, in <module>
    main()
  File "/A.I_DATA/jbnu/joonseo/gpu_test.py", line 78, in main
    trainer.train()
  File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2240, in train
    return inner_training_loop(
  File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2555, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
  File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/transformers/trainer.py", line 3745, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
  File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/transformers/trainer.py", line 3810, in compute_loss
    outputs = model(**inputs)
  File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/accelerate/utils/operations.py", line 818, in forward
    return model_forward(*args, **kwargs)
  File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/accelerate/utils/operations.py", line 806, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 44, in decorate_autocast
    return func(*args, **kwargs)
  File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/peft/peft_model.py", line 1719, in forward
    return self.base_model(
  File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 197, in forward
    return self.model.forward(*args, **kwargs)
  File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 175, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/transformers/utils/generic.py", line 969, in wrapper
    output = func(self, *args, **kwargs)
  File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 708, in forward
    loss = self.loss_function(logits=logits, labels=labels, vocab_size=self.config.vocab_size, **kwargs)
  File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/transformers/loss/loss_utils.py", line 64, in ForCausalLMLoss
    loss = fixed_cross_entropy(logits, shift_labels, num_items_in_batch, ignore_index, **kwargs)
  File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/transformers/loss/loss_utils.py", line 38, in fixed_cross_entropy
    loss = loss / num_items_in_batch
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!
  0%|                                                                                                                          | 0/2395 [00:03<?, ?it/s]
```

I want to first know that this problem is come from accelerate or not. If it is, what can I do or what did I do wrong? If it is not, may I leave the issue to `SFTTrainer`? or other libraries?

### Expected behavior

Well work on 70B QLoRA

**Comment by S1ro1** [comment]
Can you try running it with `torchrun` instead of Python and see if it makes any difference. Also could you provide the config that your `accelerate` uses, if any?

**Comment by Indigo-Coder-github** [comment]
I don't use additional configs for `accelerate`, only set `accelerate env`.
When I ran `torchrun gpu_test.py`, it also behaved like `accelerate launch gpu_test.py`, only use GPU:0.
```bash
Loading checkpoint shards:  30%|███████████████████████████████████████▎                                                                                           | 9/30 [00:08<00:19,  1.08it/s]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/A.I_DATA/jbnu/joonseo/gpu_test_origin.py", line 82, in <module>
[rank0]:     main()
[rank0]:   File "/A.I_DATA/jbnu/joonseo/gpu_test_origin.py", line 29, in main
[rank0]:     model = AutoModelForCausalLM.from_pretrained(
[rank0]:   File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 571, in from_pretrained
[rank0]:     return model_class.from_pretrained(
[rank0]:   File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 309, in _wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4574, in from_pretrained
[rank0]:     ) = cls._load_pretrained_model(
[rank0]:   File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 5031, in _load_pretrained_model
[rank0]:     disk_offload_index, cpu_offload_index = _load_state_dict_into_meta_model(
[rank0]:   File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/A.I_DATA/jbnu/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 784, in _load_state_dict_into_meta_model
[rank0]:     param = empty_param.to(tensor_device)  # It is actually not empty!
[rank0]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 448.00 MiB. GPU 0 has a total capacity of 44.39 GiB of which 42.38 MiB is free. Including non-PyTorch memory, this process has 44.26 GiB memory in use. Of the allocated memory 43.83 GiB is allocated by PyTorch, and 15.19 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[rank0]:[W611 10:18:28.994971401 ProcessGroupNCCL.cpp:1476] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
```

To find the solution, I read the official doc. And then I add the some code like below. Below code recoginzed the multi-gpu but reproduced the OOM after loading the shards 100%.
```python
    model_id = "meta-llama/Llama-3.3-70B-Instruct"
    
    # Below line is newly added.
    accelerator = Accelerator()

    quantization_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_use_double_quant=True,
    )

    lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "k_proj", "v_proj", "out_proj"],
    task_type="CAUSAL_LM",
    )

    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        device_map={"": accelerator.device}, # previous version is "auto"
        quantization_config=quantization_config,
        torch_dtype=torch.bfloat16,
        low_cpu_mem_usage=True,
    )
```

**Comment by Indigo-Coder-github** [comment]
Finally I found the solution. I read the official docs and found the hint. Run by `accelerate launch gpu_test.py`. Also I set the `PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True`. I hope this comment will be helpful for beginners.

```python
import os
import torch
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
)
from peft import LoraConfig
from trl import SFTTrainer, SFTConfig
from datasets import load_dataset

def main():
    model_id = "meta-llama/Llama-3.3-70B-Instruct"

    # Below line is newly added.
    accelerator = Accelerator()
    
    quantization_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_use_double_quant=True,
    )

    lora_config = LoraConfig(
        r=16,
        lora_alpha=32,
        target_modules=["q_proj", "v_proj"],
        task_type="CAUSAL_LM",
    )

    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        # device_map="auto", # disable the device_map
        quantization_config=quantization_config,
        torch_dtype=torch.bfloat16,
        low_cpu_mem_usage=True,
    )
    
    tokenizer = AutoTokenizer.from_pretrained(model_id, add_eos_token=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
        
    model.config.pad_token_id = tokenizer.pad_token_id
    
    train_dataset = load_dataset("ChuGyouk/Asan-AMC-Healthinfo", split="train")

    def chat_template(example):
        example["text"] = tokenizer.apply_chat_template(
            [
                {"role": "user", "content": example['instruction']},
                {"role": "assistant", "content": example['output']},
            ],
            tokenize=False,
        )
        return example

    train_dataset = train_dataset.map(chat_template)

    sft_config = SFTConfig(
        output_dir="./fine_tuned/Llama-3.3-70B-Script-Test",
        overwrite_output_dir=True,
        do_train=True,
        max_seq_length=1024,
        per_device_train_batch_size=1,
        gradient_accumulation_steps=256,
        gradient_checkpointing=True, # newly added
        gradient_checkpointing_kwargs={"use_reentrant": False}, # newly added
        num_train_epochs=1,
        dataset_text_field="text",
        bf16=True,
    )

    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        args=sft_config,
        peft_config=lora_config,
        train_dataset=train_dataset,
    )

    print(f"--- [Process {os.getpid()}, Rank {trainer.accelerator.process_index}] 학습 시작 ---")
    trainer.train()
    print(f"--- [Process {os.getpid()}, Rank {trainer.accelerator.process_index}] 학습 완료 ---")

if __name__ == "__main__":
    main()
```
