### ISSUE TITLE
FSDP MoE PEFT hangs during forward pass

### ISSUE THREAD

**Issue by ojh31** [huggingface/accelerate#3832]
### System Info

```Shell
- `Accelerate` version: 1.10.1
- Platform: Linux-5.15.0-161-generic-x86_64-with-glibc2.39
- `accelerate` bash location: /opt/uv/venv/bin/accelerate
- Python version: 3.12.11
- Numpy version: 2.2.6
- PyTorch version: 2.9.0+cu128
- PyTorch accelerator: CUDA
- System RAM: 1003.13 GB
- GPU type: NVIDIA H100 80GB HBM3
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [x] My own task or dataset (give details below)

### Reproduction

```
#!/usr/bin/env python3
"""Minimal script to load Qwen3 MOE and run forward pass.

Accelerate config:

compute_environment: LOCAL_MACHINE
debug: false
distributed_type: FSDP
downcast_bf16: "no"
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch: BACKWARD_PRE
  fsdp_cpu_ram_efficient_loading: true
  fsdp_forward_prefetch: false
  fsdp_offload_params: false
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_sync_module_states: true
  fsdp_use_orig_params: true
machine_rank: 0
main_training_function: main
mixed_precision: "bf16"
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
"""

import torch
from accelerate import Accelerator
from peft import LoraConfig, get_peft_model
from peft.utils.other import fsdp_auto_wrap_policy
from transformers import AutoModelForCausalLM, AutoTokenizer


def main():
    torch.set_grad_enabled(False)
    # model_name = "Qwen/Qwen3-32B" # Works
    model_name = "Qwen/Qwen3-30B-A3B"  # Hangs during forward pass

    torch_dtype = torch.bfloat16

    peft_config = LoraConfig(
        r=16,
        lora_alpha=32,
        lora_dropout=0.05,
        bias="none",
        task_type="CAUSAL_LM",
        target_modules="all-linear",
    )

    accelerator = Accelerator()

    accelerator.print(f"Loading tokenizer for {model_name}...")
    tokenizer = AutoTokenizer.from_pretrained(model_name)

    accelerator.print(f"Loading model {model_name}...")
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        torch_dtype=torch_dtype,
    )

    accelerator.print("Base model loaded successfully!")

    model = get_peft_model(model, peft_config, autocast_adapter_dtype=False)
    model.print_trainable_parameters()
    accelerator.print("PEFT model created successfully!")

    fsdp_plugin = getattr(accelerator.state, "fsdp_plugin", None)
    if fsdp_plugin is not None:
        fsdp_plugin.auto_wrap_policy = fsdp_auto_wrap_policy(model)
    else:
        accelerator.print("FSDP plugin not found, skipping auto wrap policy")

    model = accelerator.prepare(model)

    accelerator.print("Model prepared successfully!")

    # Prepare input
    text = "What is the capital of France?"
    formatted_text = tokenizer.apply_chat_template(
        [{"role": "user", "content": text}],
        tokenize=False,
        add_generation_prompt=True,
    )
    accelerator.print(f"\nInput: {formatted_text}")

    inputs = tokenizer(formatted_text, return_tensors="pt")
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    # Forward pass
    accelerator.print("\nRunning forward pass...")
    outputs = model(**inputs, labels=inputs["input_ids"])
    loss = outputs.loss
    accelerator.print(f"Loss: {loss.item()}")

    accelerator.print("\nForward pass completed successfully!")


if __name__ == "__main__":
    main()
```

### Expected behavior

Should output "Forward pass completed successfully!". This is what happens if I either

- disable FSDP
- disable PEFT
- switch to a dense model like `Qwen/Qwen3-32B`

**Comment by ojh31** [comment]
I also found that this does not hang if I change the peft config to only effect the attention layers (QKVO) and not up/down/gate.

**Comment by SunMarc** [comment]
cc @BenjaminBossan if you have time. Also @ojh31, what is the traceback you get when you try to exit as it hangs ?

**Comment by BenjaminBossan** [comment]
I couldn't test this big model, but I tried with `hf-internal-testing/tiny-qwen3-moe`, which looks like it has the same architecture, and it worked (with 2 GPUs). @ojh31 could you please test if it's the same for you?

As for things to test, could you try setting `fsdp_cpu_ram_efficient_loading: false` in your FSDP config?

**Comment by ojh31** [comment]
Thank you both for the engagement. Upon more careful testing, I've realized that it does run, it is just monumentally slow. It takes 25x as long to run a forward pass on an MoE lora model if the lora targets the MLPs instead of just the attention, and 500x as long compared to a dense model of the same size. Is this expected / fixable? The DeepSpeed backend doesn't have anywhere near the slowdown: just 8x in total.


MoE | LoRA | Accelerate config | Forward pass time
-- | -- | -- | --
FALSE | Attention-only | Deepspeed | 1.02
FALSE | Attention-only | FSDP w/o cpu efficient loading | 1.04
FALSE | Attention-only | FSDP | 1.04
FALSE | All-linear | FSDP w/o cpu efficient loading | 1.49
FALSE | All-linear | FSDP | 1.53
FALSE | All-linear | Deepspeed | 1.73
TRUE | Attention-only | Deepspeed | 3.05
TRUE | All-linear | Deepspeed | 7.74
TRUE | Attention-only | FSDP | 21.86
TRUE | Attention-only | FSDP w/o cpu efficient loading | 22.09
TRUE | All-linear | FSDP w/o cpu efficient loading | 521.41
TRUE | All-linear | FSDP | 527.48

**Comment by BenjaminBossan** [comment]
Thanks for the further checks and sorry for the delay. This looks really strange indeed. Could you please detail what layers are actually being targeted with LoRA depending on our settings, i.e. with vs without MoE, and only attention vs all linear? AFAICT, the MoE layer should not be targeted at all, as it's not a linear layer, but apparently something must be happening.

One way to show this would be to add these lines after `get_peft_model`:

```python
    for row in model.get_layer_status():
        accelerator.print(row)
```

As I assume this will repeat identically for each layer, it's enough to show the output for the first one.

**Comment by ojh31** [comment]
Further update: most of the slowness for FSDP MoE LoRA is just during the first forward pass and is mostly in the pre_forward with no GPU operations.

First forward pass takes 8.5 minutes:
<img width="3603" height="388" alt="Image" src="https://github.com/user-attachments/assets/525ff75b-34ca-42d8-b87f-853829fb4863" />

Second identical forward pass takes 14s:
<img width="3278" height="382" alt="Image" src="https://github.com/user-attachments/assets/41d4d8a1-e818-443c-ad3a-3a50a2b189d5" />

**Comment by ojh31** [comment]
There are a lot of LoRAs, three per expert!
```
TunerLayerStatus(name='model.model.layers.47.mlp.experts.127.gate_proj', module_type='lora.Linear', enabled=True, active_adapters=['default'], merged_adapters=[], requires_grad={'default': True}, available_adapters=['default'], devices={'default': ['cpu']})
TunerLayerStatus(name='model.model.layers.47.mlp.experts.127.up_proj', module_type='lora.Linear', enabled=True, active_adapters=['default'], merged_adapters=[], requires_grad={'default': True}, available_adapters=['default'], devices={'default': ['cpu']})
TunerLayerStatus(name='model.model.layers.47.mlp.experts.127.down_proj', module_type='lora.Linear', enabled=True, active_adapters=['default'], merged_adapters=[], requires_grad={'default': True}, available_adapters=['default'], devices={'default': ['cpu']})
```

[layer_status.txt](https://github.com/user-attachments/files/23661248/layer_status.txt)

**Comment by ojh31** [comment]
Okay I have a better sense of it now. `torch.distributed.fsdp._common_utils._apply_to_modules` does a string match `fqn.startswith(new_prefix)` on the order of named_modules * named_parameters times, which in this case is 255k * 56k = 14 billion times! When I profiled it, basically the full 8.5 minutes is spent doing these string matches. I guess I'll move this issue over to pytorch.

**Comment by BenjaminBossan** [comment]
> There are a lot of LoRAs, three per expert!

Ah yes, Qwen MoE uses `nn.Linear` layers for the MoE, which many other architectures don't.

> Okay I have a better sense of it now. `torch.distributed.fsdp._common_utils._apply_to_modules` does a string match `fqn.startswith(new_prefix)` on the order of named_modules * named_parameters times, which in this case is 255k * 56k = 14 billion times! When I profiled it, basically the full 8.5 minutes is spent doing these string matches. I guess I'll move this issue over to pytorch.

Nice find, I hope it'll be fixed there soon.
