### ISSUE TITLE
Multi-node training hangs at accelerator.prepare(model)

### ISSUE THREAD

**Issue by xiabingquan** [huggingface/accelerate#412]
Recently I'm trying to launch multi-node distributed training using on two servers accelerate, but the training always hangs at accelerate.prepare(model). The detailed environment information and minimal code to reproduce the error are as follows

The config file of the main server(hosting the main process):
```
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
fp16: false
machine_rank: 0
main_process_ip: IP1
main_process_port: PORT1
main_training_function: main
num_machines: 2
num_processes: 2
```
The config file of the second server is all the same as the one above except that the `machine_rank` is 1 instead of 0.

The environmental information:
```
Python3.7.6
torch1.10.1+cu113
accelerate0.5.1
```

The minimal code to reproduce the code:
```
import torch
import torch.nn as nn
from accelerate import Accelerator

if __name__ == "__main__":
    accelerator = Accelerator()
    model = nn.Conv2d(10, 20, 3, 1, 1)
    model = accelerator.prepare(model)
```
then `accelerate launch ./main.py`

The above setting performs well on any of a single machine, but multi-node training somewhat fails. I'm pretty sure I'm using the right configuratbtw, ion file and the two servers can communicate with each other via the port PORT1.

Any reply is appreciated : )

**Comment by xiabingquan** [comment]
btw, the two servers share the exact same runtime environment.

**Comment by sgugger** [comment]
This works on our end, so in this instance, the problem is probably some communication failure on your multi-node setup.

**Comment by xiabingquan** [comment]
> This works on our end, so in this instance, the problem is probably some communication failure on your multi-node setup.

Thanks for your reply. I also think so, but I have no idea what other settings should be enabled. I've enabled the *PORT1* port in the main server so that the two servers could communicate with each other. Is there something I've missed?

**Comment by sgugger** [comment]
Maybe @pacman100 who recently debugged multi-node training on our end has more ideas? On my end, nothing comes to mind.

**Comment by pacman100** [comment]
Hello @xiabingquan , could you paste the output logs with `NCCL_DEBUG=INFO` before the launch command, e.g., `NCCL_DEBUG=INFO accelerate launch script.py args`?

**Comment by xiabingquan** [comment]
> Hello @xiabingquan , could you paste the output logs with `NCCL_DEBUG=INFO` before the launch command, e.g., `NCCL_DEBUG=INFO accelerate launch script.py args`?
> 
> See if the log has `Network is unreachable` before hanging.

Thanks for your reply :) Below is the output after adding `NCCL_DEBUG=INFO`

The output of the main server 
```
~/miniconda3/envs/lrs/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
ubuntu:13025:13025 [0] NCCL INFO Bootstrap : Using enp5s0:10.29.0.25<0>
ubuntu:13025:13025 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
ubuntu:13025:13025 [0] NCCL INFO NET/IB : No device found.
ubuntu:13025:13025 [0] NCCL INFO NET/Socket : Using [0]enp5s0:10.29.0.25<0> [1]ens7:192.168.37.25<0>
ubuntu:13025:13025 [0] NCCL INFO Using network Socket
NCCL version 2.10.3+cuda11.3

```

The output of the second server
```
~/miniconda3/envs/lrs/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
aa-ESC4000:23293:23293 [0] NCCL INFO Bootstrap : Using enp6s0:10.29.0.113<0>
aa-ESC4000:23293:23293 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation

aa-ESC4000:23293:23293 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
aa-ESC4000:23293:23293 [0] NCCL INFO NET/Socket : Using [0]enp6s0:10.29.0.113<0> [1]ens7:192.168.37.113<0>
aa-ESC4000:23293:23293 [0] NCCL INFO Using network Socket

```

**Comment by brandonbell11** [comment]
I am also having this same problem when attempting to run accelerate between two identical EC2 instances. Accelerate works perfectly fine for each one individually

**Comment by pacman100** [comment]
@xiabingquan , could you try below command on both nodes before running the code and use `192.168.37.25` as `IP1` as shown in the `ens7` entry of main server.
`export NCCL_SOCKET_IFNAME= ens7 `. 

I ran your code on distributed setup (2 nodes) but didn't face any issue. In my case, I had to set `export NCCL_SOCKET_IFNAME= enp6s0` following this issue [NCCL Network is unreachable / Connection refused when initializing DDP - distributed - PyTorch Forums](https://discuss.pytorch.org/t/nccl-network-is-unreachable-connection-refused-when-initializing-ddp/137352/2)

**Comment by xiabingquan** [comment]
> @xiabingquan , could you try below command on both nodes before running the code and use `192.168.37.25` as `IP1` as shown in the `ens7` entry of main server. `export NCCL_SOCKET_IFNAME= ens7 `.
> 
> I ran your code on distributed setup (2 nodes) but didn't face any issue. In my case, I had to set `export NCCL_SOCKET_IFNAME= enp6s0` following this issue [NCCL Network is unreachable / Connection refused when initializing DDP - distributed - PyTorch Forums](https://discuss.pytorch.org/t/nccl-network-is-unreachable-connection-refused-when-initializing-ddp/137352/2)

Thanks for your reply. Already tried that and nothing changed. I also tried running multi-node experiments via Pytorch-lightning instead of accelerate but pl got stuck in the same place. I highly doubt that it's because of my network settings but I couldn't check it in person because of COVID-19. I'll put it aside for while until I'm able to check the network settings. However, the two servers could be successfully pinged by each other server so maybe the network also works fine :( Driving me crazy

**Comment by xiabingquan** [comment]
One thing to notice is that, in the main server, the last debug message is `NCCL version 2.10.3+cuda11.3`, but the same message didn't appear on the second server.

**Comment by DogeWatch** [comment]
I have the same issues, when I use the same script and run like `NCCL_DEBUG=INFO accelerate launch --config_file /tmp/config.yaml main.py`, the error of master server is
```
NCCL_DEBUG=INFO accelerate launch --config_file /tmp/config.yaml main.py
f31e57d4-8849-429e-886f-a595642e27d6:12675:12675 [0] NCCL INFO Bootstrap : Using eth1:11.214.119.22<0>
f31e57d4-8849-429e-886f-a595642e27d6:12675:12675 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
f31e57d4-8849-429e-886f-a595642e27d6:12675:12675 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/RoCE ; OOB eth1:11.214.119.22<0>
f31e57d4-8849-429e-886f-a595642e27d6:12675:12675 [0] NCCL INFO Using network IB
NCCL version 2.10.3+cuda10.2
f31e57d4-8849-429e-886f-a595642e27d6:12675:12697 [0] NCCL INFO Channel 00/02 :    0   1
f31e57d4-8849-429e-886f-a595642e27d6:12675:12697 [0] NCCL INFO Channel 01/02 :    0   1
f31e57d4-8849-429e-886f-a595642e27d6:12675:12697 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] -1/-1/-1->0->1
f31e57d4-8849-429e-886f-a595642e27d6:12675:12697 [0] NCCL INFO Setting affinity for GPU 0 to ff,ffff0000,00fffffc
f31e57d4-8849-429e-886f-a595642e27d6:12675:12697 [0] NCCL INFO Channel 00 : 1[1a000] -> 0[1a000] [receive] via NET/IB/0
f31e57d4-8849-429e-886f-a595642e27d6:12675:12697 [0] NCCL INFO Channel 01 : 1[1a000] -> 0[1a000] [receive] via NET/IB/0
f31e57d4-8849-429e-886f-a595642e27d6:12675:12697 [0] NCCL INFO Channel 00 : 0[1a000] -> 1[1a000] [send] via NET/IB/0
f31e57d4-8849-429e-886f-a595642e27d6:12675:12697 [0] NCCL INFO Channel 01 : 0[1a000] -> 1[1a000] [send] via NET/IB/0
f31e57d4-8849-429e-886f-a595642e27d6:12675:12697 [0] NCCL INFO Connected all rings
f31e57d4-8849-429e-886f-a595642e27d6:12675:12697 [0] NCCL INFO Connected all trees
f31e57d4-8849-429e-886f-a595642e27d6:12675:12697 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
f31e57d4-8849-429e-886f-a595642e27d6:12675:12697 [0] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer
f31e57d4-8849-429e-886f-a595642e27d6:12675:12697 [0] NCCL INFO comm 0x7f5218000fa0 rank 0 nranks 2 cudaDev 0 busId 1a000 - Init COMPLETE
f31e57d4-8849-429e-886f-a595642e27d6:12675:12675 [0] NCCL INFO Launch mode Parallel

f31e57d4-8849-429e-886f-a595642e27d6:12675:12699 [0] transport/net_ib.cc:882 NCCL WARN NET/IB : Got completion from peer 11.214.138.63<50780> with error 12, opcode 0, len 0, vendor err 129
f31e57d4-8849-429e-886f-a595642e27d6:12675:12699 [0] NCCL INFO include/net.h:28 -> 2
f31e57d4-8849-429e-886f-a595642e27d6:12675:12699 [0] NCCL INFO transport/net.cc:459 -> 2
f31e57d4-8849-429e-886f-a595642e27d6:12675:12699 [0] NCCL INFO proxy.cc:351 -> 2
f31e57d4-8849-429e-886f-a595642e27d6:12675:12699 [0] NCCL INFO proxy.cc:452 -> 2 [Proxy Thread]
[E ProcessGroupNCCL.cpp:414] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  NCCL error: unhandled system error, NCCL version 2.10.3
ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error. It can be also caused by unexpected exit of a remote peer, you can check NCCL warnings for failure reason and see if there is connection closure by a peer.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 12675) of binary: /data/miniconda3/envs/env-3.8.8/bin/python
Traceback (most recent call last):
  File "/data/miniconda3/envs/env-3.8.8/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
======================================================
main.py FAILED
```

and the error of the second server is 
```
NCCL_DEBUG=INFO accelerate launch --config_file /tmp/config.yaml main.py
4a72aede-30e1-43ba-873a-de73fb9d7c94:12545:12545 [0] NCCL INFO Bootstrap : Using eth1:11.214.138.63<0>
4a72aede-30e1-43ba-873a-de73fb9d7c94:12545:12545 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
4a72aede-30e1-43ba-873a-de73fb9d7c94:12545:12545 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/RoCE ; OOB eth1:11.214.138.63<0>
4a72aede-30e1-43ba-873a-de73fb9d7c94:12545:12545 [0] NCCL INFO Using network IB
4a72aede-30e1-43ba-873a-de73fb9d7c94:12545:12566 [0] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] 0/-1/-1->1->-1
4a72aede-30e1-43ba-873a-de73fb9d7c94:12545:12566 [0] NCCL INFO Setting affinity for GPU 0 to ff,ffff0000,00fffffc
4a72aede-30e1-43ba-873a-de73fb9d7c94:12545:12566 [0] NCCL INFO Channel 00 : 0[1a000] -> 1[1a000] [receive] via NET/IB/0
4a72aede-30e1-43ba-873a-de73fb9d7c94:12545:12566 [0] NCCL INFO Channel 01 : 0[1a000] -> 1[1a000] [receive] via NET/IB/0
4a72aede-30e1-43ba-873a-de73fb9d7c94:12545:12566 [0] NCCL INFO Channel 00 : 1[1a000] -> 0[1a000] [send] via NET/IB/0
4a72aede-30e1-43ba-873a-de73fb9d7c94:12545:12566 [0] NCCL INFO Channel 01 : 1[1a000] -> 0[1a000] [send] via NET/IB/0
4a72aede-30e1-43ba-873a-de73fb9d7c94:12545:12566 [0] NCCL INFO Connected all rings
4a72aede-30e1-43ba-873a-de73fb9d7c94:12545:12566 [0] NCCL INFO Connected all trees
4a72aede-30e1-43ba-873a-de73fb9d7c94:12545:12566 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
4a72aede-30e1-43ba-873a-de73fb9d7c94:12545:12566 [0] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer
4a72aede-30e1-43ba-873a-de73fb9d7c94:12545:12566 [0] NCCL INFO comm 0x7fc730000fa0 rank 1 nranks 2 cudaDev 0 busId 1a000 - Init COMPLETE

4a72aede-30e1-43ba-873a-de73fb9d7c94:12545:12568 [0] transport/net_ib.cc:882 NCCL WARN NET/IB : Got completion from peer 11.214.119.22<56528> with error 12, opcode 0, len 0, vendor err 129
4a72aede-30e1-43ba-873a-de73fb9d7c94:12545:12568 [0] NCCL INFO include/net.h:28 -> 2
4a72aede-30e1-43ba-873a-de73fb9d7c94:12545:12568 [0] NCCL INFO transport/net.cc:459 -> 2
4a72aede-30e1-43ba-873a-de73fb9d7c94:12545:12568 [0] NCCL INFO proxy.cc:351 -> 2
4a72aede-30e1-43ba-873a-de73fb9d7c94:12545:12568 [0] NCCL INFO proxy.cc:452 -> 2 [Proxy Thread]
[E ProcessGroupNCCL.cpp:414] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  NCCL error: unhandled system error, NCCL version 2.10.3
ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error. It can be also caused by unexpected exit of a remote peer, you can check NCCL warnings for failure reason and see if there is connection closure by a peer.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 12545) of binary: /data/miniconda3/envs/env-3.8.8/bin/python
Traceback (most recent call last):
  File "/data/miniconda3/envs/env-3.8.8/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
======================================================
main.py FAILED
```

**Comment by DogeWatch** [comment]
I found the way to solve this issue: https://github.com/NVIDIA/nccl/issues/426

**Comment by xiabingquan** [comment]
> 

Thanks a lot!!! I'll try it later : )

**Comment by xiabingquan** [comment]
> I found the way to solve this issue: [NVIDIA/nccl#426](https://github.com/NVIDIA/nccl/issues/426) use command like `NCCL_IB_GID_INDEX=3 NCCL_DEBUG=INFO accelerate launch --config_file /tmp/config.yaml main.py`


Thanks a lot!!! I'll try it later : )

**Comment by eladbitton** [comment]
For me this didn't work on kubernetes cluster with the same error message. 
The issue was that a shared memory was not available to the pod. Fixed it by adding a shared memory volume to the deployment yaml:
        - mountPath: /dev/shm
          name: gpus-shared-memory
      volumes:
        - name: gpus-shared-memory
          emptyDir:
            medium: Memory
            sizeLimit: 128Mi

More information here: https://www.sobyte.net/post/2022-04/k8s-pod-shared-memory/
