### ISSUE TITLE
RuntimeError: Address already in use

### ISSUE THREAD

**Issue by ADaBenxiong** [huggingface/accelerate#508]
What is the reason of 'RuntimeError: Address already in use', 'RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled system error, NCCL version 2.7.8'
When I implement “accelerate test”，can I run two scripts at the same time?

**Comment by sgugger** [comment]
You have to specify a different port for the second script if the first one is not finished (but then you are more likely to get OOM since the GPUs have a limited memory).

**Comment by ADaBenxiong** [comment]
Thanks a lot, I have resolved my question, I need to add the "--main_process_port".
Thank you very much
